### ISSUE TITLE
$ is not a function, line: 22

### ISSUE THREAD

**Issue by Naki** [lukasoppermann/html5sortable#108]
Hello,
I was using plugin since 1.1.6 version, and everything was OK till version 0.2.3 where [line 9](https://github.com/voidberg/html5sortable/blob/master/dist/html.sortable.js#L9) changed from **"jquery"** to **"$"**.
Is it intended ?

Now I get error like in subject with standard jQuery (1.11.3) ready to run scripts: `jQuery(function($) { /*...*/ }`

Regards

**Comment by lukasoppermann** [comment]
Hey, can you please update? It should be fixed with the latest release. v0.2.4

**Comment by Naki** [comment]
v0.2.4 works good, thank You!

**Comment by lukasoppermann** [comment]
Sure, thanks for noticing, I added a test, so that this can not happen again. :)
