### ISSUE TITLE
Add cookie ability to sort lists to what they were on refresh

### ISSUE THREAD

**Issue by silkcom** [lukasoppermann/html5sortable#11]
I'd love to see an option to add a "cookie_name" variable on .sortable and have it keep the items in the order that I put them in.  

http://stackoverflow.com/questions/1370417/jquery-ui-sortable-and-cookie

Not overly difficult to do, but it'd be much cleaner to have it in line.

**Comment by Manduro** [comment]
I'd rather have this functionality implemented using localStorage.

**Comment by lukasoppermann** [comment]
This seems to be more application logic. Normally you would update the data in your db. If your app solely relies on cookies or local storage this is still app logic specific to your use case.
