### ISSUE TITLE
After removing items, disabled items may be dragged.

### ISSUE THREAD

**Issue by YokiToki** [lukasoppermann/html5sortable#119]
I was wanted to create clonable item. After drag&copy item, when trying to return item in first list I call to ui.item.remove(); because clonable item must be unique in first list. But, after remove, items has class diabled `items: ':not(.disabled)'` may be dragged.

Here is fiddle: https://jsfiddle.net/04nt0d0t/

**Comment by lukasoppermann** [comment]
Works fine for me, please check again that you have no type, because you are using a class named `diabled` instead of `disabled`. So maybe you have a typo somewhere?

**Comment by YokiToki** [comment]
@lukasoppermann, yes it's typo, but elements have same class and this is not the case. When performing following steps disabled elements may be dragged.
![screenshoot](https://cloud.githubusercontent.com/assets/1845813/7586332/6694f074-f8c5-11e4-8984-eb6d41ef0991.png)

**Comment by lukasoppermann** [comment]
Ahh, thanks for the diagram, I can replicate your problem and will investigate it.
