### ISSUE TITLE
Prevent URL displaying in Chrome Ghost drag image

### ISSUE THREAD

**Issue by nevf** [lukasoppermann/html5sortable#13]
If you have `<li><a href="http:\\www.somesite.com">Drag Me"</a></li>` as a dragable element Chrome displays a Ghost image that includes the URL. I've done lots of Google'ing and found various info on Ghost images, but no easy way to not have the URL included.

Interestingly jquery-sortable http://johnny.github.io/jquery-sortable/ doesn't show the URL however after studying the code & css and checcking in the debugger I can't work out how it resolves this issue.

 I realize this isn't a html5sortable issue but since that's what I'm using I'm hoping someone here may be able to help.

**Comment by nevf** [comment]
I was able to remove all the href usage to resolve this and it now looks great and works well. 

I also found a very good article "Setting a custom ghost image when using HTML5 drag and drop" http://www.kryogenix.org/code/browser/custom-drag-image.html which provided me with another option. This may be useful to others.

**Comment by lukasoppermann** [comment]
Should get fixed by #77

**Comment by lukasoppermann** [comment]
This should be fixed by #77 if the issue persists with the new version `v0.2.5` please reopen the issue.
