### ISSUE TITLE
Missing semicolon before (function(){...})

### ISSUE THREAD

**Issue by JoshWillik** [lukasoppermann/html5sortable#136]
I concatenate and minify all my code when building web applications.
I was seeing an error in firefox that said 

```
TypeError: (intermediate value)(...) is not a function
```

I eventually tracked this down to the first line of html5sortable.js.

Where it says

``` js
(function(root, factory) {
```

it should say

``` js
;(function(root, factory) {
```

Without the leading semicolon, the self invoking anonymous function will try to execute the result of whatever expression comes before it as a function.

```
```

**Comment by lukasoppermann** [comment]
Hey @JoshWillik, I understand your problem, but I think it would be the responsibility of the function before, to correct close itself off with a semicolon in the end.

Also when concatenating the script should add the semicolons if needed.

**Comment by JoshWillik** [comment]
@lukasoppermann I can see why you'd say that.

I'm still of the opinion that a single extra character is a small price to pay for library stability even if the other guy is technically in the wrong. It's really quite tricky to dig through a 12000 line `vendor.js` to find the problem.

**Comment by lukasoppermann** [comment]
Hey, I see that, my "problem" is actually not that I do not want to add the semicolon, but rather that the whole `umd` wrapper is added via a gulp task which does not add the `;` beforehand as it actually is not the "correct way". 

I will check if there is an easy way to add this, I just do not necessarily want to add a huge overhead for something that is actually not an error. :)

**Comment by JoshWillik** [comment]
Much appreciated, thanks :)

For the record, I've [pinged the issue](https://github.com/enyo/dropzone/issues/589) on the other library where the real error is, but it's been open for over a year.

**Comment by lukasoppermann** [comment]
Okay, I send a PR to the gulp-umd plugin and it was merged immediately, very nice. So from now on the files will have a ; in the beginning. #138

This will be in the next release.

**Comment by JoshWillik** [comment]
Thanks! I really appreciate the time :)
