### ISSUE TITLE
sortable broken on IE8

### ISSUE THREAD

**Issue by hnguyen08** [lukasoppermann/html5sortable#144]
Cannot drag-and-drop list elements at the [example site](http://lukasoppermann.github.io/html5sortable/examples/index.html) on IE8.  IE9 works fine.

The documentation says support for IE5.5+ (needs testing), so can this be updated, or support added for older IE's?

**Comment by lukasoppermann** [comment]
Hey, IE8 is currently not supported, as supporting it requires much work and also means we can not move forward with new features as so many things are not supported. 

Even if we would load up the plugin with tons of polyfills we would probably not get new features to work.

So maybe if you really need old browser support you could move to jquery UI?

I updated the readme though.
