### ISSUE TITLE
Copy and overwrite instead of move and insert?

### ISSUE THREAD

**Issue by grandehombre** [lukasoppermann/html5sortable#146]
Hi,
I have a requirement where I need to present the user with a number of small grids (usually 12-16 rows), where he can move items from one grid to another.
The grids represent telephone quick-dial pads.
The requirements is to be able to enter names and numbers in rows in that grid and then be able to move them around, as the user pleases.

Most sortables move an item from one list to another by deleting it from the source and inserting it in the target.
I am looking for something that will allow me to copy the item from the source and overwrite the target item.

Keep in mind that all grids are fixed length, so they already have rows in them, so the user will be dragging and dropping onto an existing row.

As an example, (using the attached image), I'd want to be able to grab grid 1, row 6 (Porsche) and move it to grid 2, row 39 (Mazda). That should result in grid 1, row 6 being blank and grid 2, row 39 saying Porsche.

I'd be just as happy if the event handler that fires off when the user drops the item, specifies the source and target components and rows. That way, I could manage the data transfer from one component to the other.

I hope this makes sense.

![image](https://cloud.githubusercontent.com/assets/3350871/8173189/2ad6255e-140d-11e5-9c09-844b5d6217f2.png)

**Comment by lukasoppermann** [comment]
Hey, this is a rather specific request. I am happy to accept a PR for a separate overwrite mode.

This:
> I'd be just as happy if the event handler that fires off when the user drops the item, specifies the source and target components and rows. That way, I could manage the data transfer from one component to the other.

sounds very sensible and most (if not all) of this should already be working. (Check out the demo html to see how to listen to the event. https://github.com/lukasoppermann/html5sortable/blob/master/docs/index.html#L305)

If you find something missing, please send a PR for that. Thanks.
