### ISSUE TITLE
IE fix for ghost prevents other events like click

### ISSUE THREAD

**Issue by afaenger** [lukasoppermann/html5sortable#148]
I've a list of items which can be clicked (&lt;a> tags). However, due to the IE fix for ghost image, this is not possible anymore since the mousedown event handler calls dragDrop() which seems to prevent any other event.

If I remove the mousedown handler code, then it works as expected. Other browsers like firefox or chrome are not affected.

**Comment by lukasoppermann** [comment]
True, but this will mean it will not work in IE. Why can't you just use a handle?

**Comment by afaenger** [comment]
I can't use a handle since the whole item must be clickable. The list is also quite large and I don't want to show an additional element as the drag and drop function is something which is used only by "advanced" users.
Isn't it possible to at least turn off the IE workaround or make it configurable?

**Comment by lukasoppermann** [comment]
Hey @afaenger,
this should be the spot where your problem arises from:
https://github.com/voidberg/html5sortable/blob/master/src/html.sortable.src.js#L166-L174

Feel free to send a PR which changes the following:
1. Add an options item: `disableIEFix` with a default set to `false`
2. Add a check for it at the mentioned position to disabled it when set to true

**Comment by afaenger** [comment]
PR has been sent

**Comment by lukasoppermann** [comment]
Thanks.
