### ISSUE TITLE
Trying to add knockout binding for it, but end up with a copy of an item

### ISSUE THREAD

**Issue by pitus** [lukasoppermann/html5sortable#156]
First of all, the `module.exports = sortable;` at the end of source fails if not using AMD/Require.

I've been trying to add a knockout binding for this plugin (somewhat based on http://www.knockmeout.net/2011/05/dragging-dropping-and-sorting-with.html) and update my `observableArray` in the `sortupdate` like this:

`var item = list()[ui.oldElementIndex];
list.remove(item);
list.splice(ui.elementIndex, 0, item);`

where `list` is a closure with the `valueAccessor()` - the `observableArray` I'm trying to update.

What happens is that after the `splice` the list gets re-built by knockout and ends up with an extra element in the original position - one that cannot be dragged anymore (as the `.sortable` has not been applied to it).

I'm guessing that `observableArray` updates such as `.splice` are optimized and only re-render changes in the `foreach` binding - and, indeed, if I extract the list() first and move the item in the regular array first, then re-apply it to the list(arr), all seems to be fine - but I just lost the performance optimization and the entire view had to be re-built as a result.

Does anyone have a suggestion how to get this working with the above list.remove() and list.splice() ? (note that I'm now just moving some items in the list and not use splice as I'm afraid the ui.elementIndex might be wrong after the initial list.remove when moving an element up/down...

**Comment by lukasoppermann** [comment]
Hey @pitus,
I did not read your full issue, but will do so soon, just on the first line: There is no `module.exports = sortable;` in the end. You are loading the wrong file. Please use the one from the `dist` directory NOT the file from the src directory.

I will read the rest soon and try to answer/fix/help.

**Comment by pitus** [comment]
Thanks for the quick answer on the module.exports.
As for the rest, I may have found the problem with using knockout alongside the html.sortable - there is some kind of a conflict with the data attached to each element (I'm yet to narrow it down to specifics, but when I don't update the observable array causing it to update the UI, it seems to work fine) - when knockout updates UI after the change, it must be overriding some of the attached data confusing html.sortable. I'll let you know more once I analyze your code and figure out what's stored where that might potentially get messed up by knockout.

**Comment by lukasoppermann** [comment]
Awesome, please do, happy to try making it work with knockout once you find
the problem. Feel free to describe the problem or send a PR. Thanks

On Sat, Jun 27, 2015, 1:38 PM pitus notifications@github.com wrote:

> Thanks for the quick answer on the module.exports.
> As for the rest, I may have found the problem with using knockout
> alongside the html.sortable - there is some kind of a conflict with the
> data attached to each element (I'm yet to narrow it down to specifics, but
> when I don't update the observable array causing it to update the UI, it
> seems to work fine) - when knockout updates UI after the change, it must be
> overriding some of the attached data confusing html.sortable. I'll let you
> know more once I analyze your code and figure out what's stored where that
> might potentially get messed up by knockout.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voidberg/html5sortable/issues/156#issuecomment-116017431
> .
> 
> ## 
> 
> —
> _veare_
> Lukas Oppermann

M lukas@vea.re
W www.vea.re
P +49 163 162 69 47

**Comment by pitus** [comment]
OK, I think I finally know what's going on ...

It's not so much a conflict but rather, the knockout.foreach UI update optimization.
If I have an observableArray bound to foreach, knockout will detect changes in it and only apply these changes to the UI (moving/removing/adding items as needed based on the change).
Because HTML.sortable has already moved the UI element to the new location, knockout re-applies the same move again to it when updating the UI (foreach binding), this results in another UI item being moved as the indexing may be slightly off.

Here's hot to reproduce it:
1) create an observableArray with [1,2,3,4] items, bind it to foreach showing numbers
2) apply HTML.sortable to it and in the `sortupdate` move the matching dragged item to match the UI in the underlying array and then call valueHasMutated on the observableArray.
3) now drag item [0] -> [3], all is fine, both arrays are in sync [2,3,4,1]
4) now drag item [2] -> [1], notice how UI now has [2,1,4,3] but observable has [2,4,3,1] it's because foreach, based on the change from [2,3,4,1] to [2,4,3,1] updated the UI further, moving 1 (not sure why from [3] to [1] but that matches the oldindex to index while [2] to [1] was oldElementIndex to elementIndex.

To remedy this, I've added a call to `ko.utils.domData.clear(element);` in the sortable ko binding just before calling the `valueHasMutated()` on our observableArray and it all seems to be OK now.
This is not the ideal solution, however as it forces knockout to re-render the entire list instead of realizing that it's already in the right order and my only need any individual binding of elements (in our case as I do set other observables after the drop). I'll see if I can stop the UI reordering by foreach.
