### ISSUE TITLE
After sorting, hover stays active on unhovered items

### ISSUE THREAD

**Issue by shafiry** [lukasoppermann/html5sortable#159]
This is a weird bug I have been getting, and hard to reproduce consistently. When you reorder a list item, the new item that takes it place maintains a hover state on it, as in the css believes it is being hovered. This can only be removed by re-hovering over it and then leaving. Go on the jsfiddle below, and sort item 1 into a different position, such as into the 5th or 6th. Then item 2, which is in the first place, maintains a hover state. If it does not work the first time, keep trying.

http://jsfiddle.net/wm297odw/4/

Any clue why this would happen?

**Comment by lukasoppermann** [comment]
This could maybe be fixed with https://github.com/voidberg/html5sortable/pull/87

**Comment by lukasoppermann** [comment]
This should/could be fixed in the `0.3.0` release, can you please check it out @shafiry? Thanks.

**Comment by delcon** [comment]
I have had the same issue repeatedly.
This can be solved by useing `hoverClass: 'is-hovered'`

**Comment by lukasoppermann** [comment]
Closing this, as it should be fixed, please let me know if is is still an issue.
