### ISSUE TITLE
Why does dragend get triggered in drop?

### ISSUE THREAD

**Issue by shafiry** [lukasoppermann/html5sortable#160]
On [line 336](https://github.com/voidberg/html5sortable/blob/master/src/html.sortable.src.js#L336) of src/html.sortable.src.js, the dragend event is triggered. This causes the event to happen twice, since it also happens on a normal drop. Why does this event get triggered explicitly on that line?

**Comment by lukasoppermann** [comment]
Good questions, we should investigate this, did you try removing it and testing all examples? Maybe including a console output, to check if dragend always fires?
