### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by jaruba** [lukasoppermann/html5sortable#161]
I installed `html5sortable` through npm:

```
npm install html5sortable
```

in my module I set:

```
require('html5sortable');
```

the first time I use `.sortable()` I get:

```
Uncaught ReferenceError: document is not defined
```

I know for a fact that in NW.js modules the `document` object is located at `window.document`.
Adding:

```
typeof window.document.createElement('span').dragDrop === 'function'
```

to this line: https://github.com/voidberg/html5sortable/blob/master/dist/html.sortable.js#L177
fixes this issue.

**Comment by lukasoppermann** [comment]
Should be fixed by #165
