### ISSUE TITLE
flicker when dragging between items

### ISSUE THREAD

**Issue by jaruba** [lukasoppermann/html5sortable#162]
Recorded the issue: https://youtu.be/w7SHoj7elv8

**Comment by jasonspick** [comment]
I have seen this issue as well and when dealing with angular and 2 way data binding, it can make a mess of your arrays.

**Comment by lukasoppermann** [comment]
@jasonspick any Idea on how to fix it? If so, please let us know.

**Comment by filipe-nunes** [comment]
Any news on this?

**Comment by filipe-nunes** [comment]
It seems there are issues if you have padding on top and/or bottom of the elements you are trying to sort (at least, that was my problem!). Try changing padding to margin, the result will be much smoother

**Comment by delcon** [comment]
I have had the same issue. fiddeling with the placeholder css can improve it.
