### ISSUE TITLE
IE10/11: User is able to remove elements from the page after highlighting and dragging

### ISSUE THREAD

**Issue by hnguyen08** [lukasoppermann/html5sortable#163]
In IE 10/11 only (tested IE10 and IE11, not occurring in Chrome or Firefox or IE9 surprisingly):
1. Visit the [demo page](http://lukasoppermann.github.io/html5sortable/examples/index.html)
2. Scroll down to the section with the handles under "Connected Lists"
3. Highlight a few elements of the list.  In the picture below, I highlighted the subitems of Item 2 through Item 5
4. Use the handle to drag one of the highlighted elements to another part of the list.  In the picture below, I dragged Item 5 to above Item 2
5. See that the elements have disappeared

Step 3:
![image](https://cloud.githubusercontent.com/assets/2112727/8830578/ee28d51e-306a-11e5-9c3c-e3557b5419a3.png)

Step 4:
![image](https://cloud.githubusercontent.com/assets/2112727/8830586/fce74ce8-306a-11e5-8110-32a804bac5d3.png)

**Comment by ncareau** [comment]
Confirmed on IE11   11.63.10586.0

Any quick fix on this issue ?

**Comment by iArnoldo** [comment]
Anything new to this issue?

**Comment by lukasoppermann** [comment]
Hey, I do not have any IE10/11 available for testing.

Are there any errors in the console? @iArnoldo ?

Can anybody pin-point the bug and send a PR to fix it?

**Comment by jneb** [comment]
Probably the same bug as #424
