### ISSUE TITLE
Restrict dragging to handle

### ISSUE THREAD

**Issue by bennyschudel** [lukasoppermann/html5sortable#166]
When there is another element with > draggable="true" < within the element, restricting dragging to the handle does not work anymore. I guess it needs a check on dragstart if it is the handle element or not.

**Comment by kshipp** [comment]
Doesn't work on mobile.  :(

**Comment by lukasoppermann** [comment]
Are you talking about nested elements. This seems to work fine on my machine. If this issue persists, please reopen with a demo showing the issue, thank you.
