### ISSUE TITLE
Sortable List to Sortable Grid

### ISSUE THREAD

**Issue by jastuder** [lukasoppermann/html5sortable#167]
I am not sure if I am missing it but is there support to move a Sortable List (Any list really) into a Sortable Grid. The use case I am trying to perform is having a list of available items and then the user can drag these items into different buckets based on the item type.

**Comment by lukasoppermann** [comment]
Are you asking for connected lists? This is possible. How you setup your lists (as a Grid or List) is up to you, so you should be able to do this.
