### ISSUE TITLE
Really fast dragging doesn't trigger

### ISSUE THREAD

**Issue by juni-vogt** [lukasoppermann/html5sortable#175]
If you flick your mouse really fast while dragging a sortable item, it is dragged but the plugin doesn't seem to notice it. I've included a gif of the demo page in which also the parent element's colour changes while :active
![issue](https://cloud.githubusercontent.com/assets/4030513/9185264/9d93f002-3fba-11e5-807e-d6b40f9136fa.gif)
Tested on OSX in newest stable versions of Chrome and Opera. Safari and Firefox seem to work expectedly.

**Comment by lizzielizzielizzie** [comment]
I believe this is because you are dragging the element to an area outside of the list. See issue #23

**Comment by kaffarell** [comment]
The issue is not present anymore in recent builds
