### ISSUE TITLE
Any way to manually fire 'dragstart' on sortable element?

### ISSUE THREAD

**Issue by 37** [lukasoppermann/html5sortable#177]
Hey, bit of an interesting one; though I'm trying to figure out how I can manually trigger 'dragstart' without actually clicking and dragging on a draggable element. 

My (simplified) use case is this:

Section 1: menu w/ list of icons
- red square button
- blue square button

Section 2: Sortable box for active elements
- red square element
- red square element
- blue square element

Section 1 is a menu with various buttons. I can click one of these buttons and it will generate a coloured square element at the bottom of section 2, and refresh the sortable so the new element can be dragged. 

What I'm TRYING to achieve is to be able to drag the square button icons, have it generate the element as being mid-drag and under the mouse so users can place it wherever they want inside the section. (bypassing the need to click, find / click & drag the new element, and then order it).

The way I'm thinking to achieve this is as follows;

1 > Section 1 icon button is clicked.
2 > New element is generated at the bottom of section 2
3 > Section 2 sortable is refreshed
4 > 'dragstart' event is fired for new element, and it appears under mouse 
5 > user places it inside section 2 wherever they desire. 

Steps 2 - 4 will happen instantaneously, so it will appear as if a user is clicks an icon and it transforms into an element placeholder on drag.

Any advice / thoughts would be greatly appreciated! If you have a better way of approaching this let me know :)

**Comment by lukasoppermann** [comment]
Hmm, I am not sure if this is possible. Technically you could trigger a dragstart event via jquery, but I am not sure how this will work out. Why can't you use an invisible element which the user drags and show it after a distance of X px?

**Comment by 37** [comment]
Alright I'll look into the jquery method, I initially thought of doing something similar it just didn't seem "clean". On second thought I guess it would be possible to replace the dragged invisible element from the origin container on sortupdate, which isn't as hacky as I initially thought. Thanks for getting back to me!
