### ISSUE TITLE
Sortable applied more than once to the same group triggers sortupdate more than once

### ISSUE THREAD

**Issue by dactivo** [lukasoppermann/html5sortable#179]
I have a list of divs which are sortable, I implement the event "sortupdate", but as I can add new divs to the list (there is a button to do that), I need to make the new items sortable too, because there are not if I don't call sortable again.

The result is that the event "sortupdate" is triggered more than once, the more items I add, the more it's called.

I have studied the code and I know that there are methods to remove the events with the jquery method "off()", but for some reason it's not working.

I have passed a lot of time trying to get it work, but I can't.
Help! :-)

**Comment by dactivo** [comment]
The code:

``` javascript
 $('#list_groups').sortable({
        handle:'.group_move',
        forcePlaceholderSize: true,
        placeholderClass: 'group_id',
        items: 'div.group_id'
// options
    }).on('sortupdate', function(e, ui) {

    //my code to save things
    });
```

The html:

``` html
<div id="list_groups" >
    <div id="group_id_0" class="group_id">
<!----MY HTML-->
</div>
    <div id="group_id_1" class="group_id">
<!----MY HTML-->
</div>
<!---many more and the new ones--->
</div>
```

**Comment by jamesjieye** [comment]
I had a similar issue that the 'sortupdate' triggered multiple times when I added items to that list. It turns out it is caused by my mistakenly called `.bind('sortupdate', onListSorted)` multiple times. I changed it to `.unbind('sortupdate').bind('sortupdate', onListSorted)` and it is fixed.

Hope it helps.

**Comment by lukasoppermann** [comment]
Ahh, now I understand, this is a jQuery limitation, as on is a jQuery method. If you use it twice without unbinding it will fire twice. So @jamesjieye's advice is correct.
