### ISSUE TITLE
Rails gem

### ISSUE THREAD

**Issue by ened** [lukasoppermann/html5sortable#180]
A rails gem would be fantastic.

**Comment by lukasoppermann** [comment]
You import javascript libraries using gems? How would you do this? is it just another config? Does any other js project use gems?

**Comment by ened** [comment]
Hi @lukasoppermann, the gem would be used for Ruby on Rails projects.
That way, a rails user can simply add 

```
gem 'html5sortable.js-rails'
```

to their `Gemfile`. This would then fetch all JS and other resources, bundle them with the applications central asset pipeline (perhaps minify and concatenate) and automatically update whenever you upload a new version and the user runs the `bundle` command. Neat!

A similar thing was done recently here: https://github.com/dsmorse/gridster.js

If you are interested, I can try preparing a PR for this.

**Comment by lukasoppermann** [comment]
Hey @ened, If you could prepare a PR that would be great.

**Comment by dsandstrom** [comment]
Use [Rails Assets](https://rails-assets.org/#/components/html.sortable) instead, which uses the already existing bower package:
```ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-html.sortable'
end
```
