### ISSUE TITLE
Handle doesn't count when dragging begins from a link

### ISSUE THREAD

**Issue by akondo06** [lukasoppermann/html5sortable#181]
Hi,
I got to use the plugin in a project and was wondering why this was happening.
Check:
https://jsfiddle.net/5cg42sfo/3/

When you **drag the link**.. the **dragstart** is triggered. Not sure if it's a plugin issue.
Tested in **Firefox 40.0.3** and **Chrome 45.0.2454.101 m**

Looking forward for the fix!

**Comment by akondo06** [comment]
Made it work by setting attribute **draggable** to **false** on the link element. 
Still .. should be handled in a better way.

**Comment by Mushr0000m** [comment]
Hi, Same issue with img tag. I have set the handle param, but for some reason, if there is an img tag inside my sortable element list (in my case it's for a gallery) then the img tag still act as a draggable element. So need to add draggable="false" on the img. Then the handles works.

**Comment by lukasoppermann** [comment]
This should be fixed, if it persists, please reopen.
