### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by seanpaulkelley** [lukasoppermann/html5sortable#182]
I am using your html5sortable source in following this tutorial:
http://josephndungu.com/tutorials/ajax-sortable-lists-rails-4

I am getting this error on chrome console when using in Rails:
Uncaught ReferenceError: module is not defined(anonymous function) @ html.sortable.self.js?body=1:433

I noticed that the original tutorial did not have this error because it uses an older verion of your file:
html.sortable.js

I was going to use the older version too but I see that it does not allow me to drag items to position #1.

It looks like I get this error starting with your May 1 version:
https://github.com/voidberg/html5sortable/commit/72bddf1c88c53b5ed29b6c087e06ce7e3a54a9d5#diff-f42dd2e6f1fc935a2fd8a4911d6dfb1a 

Your current demo demostrates error too:
http://lukasoppermann.github.io/html5sortable/examples/index.html

**Comment by lukasoppermann** [comment]
Hey, are you should not be using the source code. The error occurs in the demo, because the demo uses the source code, this is so that when developing the module you see your changes immediately. Please use the **dist** version (best install via bower) and let me know if this fixes the error.

**Comment by seanpaulkelley** [comment]
thanks- I do not currently use bower, so I will need to work out how to incorporate that into rails and heroku.  I will get back with you on how that works

**Comment by lukasoppermann** [comment]
Well, maybe you can try to use the version from the dist folder first. This
should already work.

On Sat, Oct 10, 2015, 2:09 PM Sean Kelley notifications@github.com wrote:

> thanks- I do not currently use bower, so I will need to work out how to
> incorporate that into rails and heroku. I will get back with you on how
> that works
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/voidberg/html5sortable/issues/182#issuecomment-147082455
> .
> 
> ## 
> 
> —
> _veare_
> Lukas Oppermann

M lukas@vea.re
W www.vea.re
P +49 163 162 69 47

**Comment by seanpaulkelley** [comment]
thanks very much- that works and I get a minified version :-)
