### ISSUE TITLE
Can't drag to an empty connected list

### ISSUE THREAD

**Issue by nickfederighi** [lukasoppermann/html5sortable#183]
With two or more connected lists, if all items are removed from a list, I can't add an item back to the original list. There is also no placeholder item shown if you try to move an element from one connected list to another empty connected list.

This is reproducible in the examples:

http://lukasoppermann.github.io/html5sortable/examples/index.html

**Comment by lukasoppermann** [comment]
Hey, you can solve this issue by adding a padding to the list.

It just does not work if the list is 0px heigh.
