### ISSUE TITLE
cannot scroll while dragging

### ISSUE THREAD

**Issue by reinierstam** [lukasoppermann/html5sortable#185]
while dragging an element i cannot scroll anymore.

is there a way to fix this?

**Comment by shejuly** [comment]
+1

**Comment by splifo** [comment]
+1

**Comment by ckarmy** [comment]
+1

**Comment by wakirin** [comment]
My temporary solution:

```
var _x, _y;

function cursorScroll(e){
	if (_x && _y && e.which == 1) {
		window.scrollBy(e.clientX - _x, e.clientY - _y);
	}
	_x = e.clientX;
	_y = e.clientY;
}

sortable('.js-grid')[0].addEventListener('sortstart', function(e) {
    document.getElementsByClassName('js-grid')[0].addEventListener('mousemove', cursorScroll);
    //...
});

sortable('.js-grid')[0].addEventListener('sortstop', function(e) {
	document.getElementsByClassName('js-grid')[0].removeEventListener('mousemove', cursorScroll);
	//...
});
```
It's not unlock scroll, but when you dragging object you can scroll page with cursor, just move cursor to the bottom.

**Comment by lukasoppermann** [comment]
Hey @Wakirin,
do you think you could turn this into a PR with tests?

**Comment by Wakirin** [comment]
@lukasoppermann, I can try, but later.

**Comment by wakirin** [comment]
I created example file with long list http://dev.coding.kz/html5sortable/examples/long-list.html
and there scrolling working without this function (cursorScroll). lol.
I don't understand, when I did the same on my project it's not worked.

@lukasoppermann I think issue can be closed?

**Comment by lukasoppermann** [comment]
Hmm, this is weird indeed. Did you test it in the same browser & same version of the package?

**Comment by wakirin** [comment]
Package version the same.
Browser Chrome, current version 56.0.2924.87 (64-bit), but don't know what version when I tested it on my project.
Again test it on my project, I can, but later.

**Comment by wakirin** [comment]
I was tested it again on my project without this function (cursorScroll), and it's working.
Don't know what happened, maybe some conflicts or I just hurried.

**Comment by lukasoppermann** [comment]
Good to know, thanks.

**Comment by D-ominik** [comment]
`I created example file with long list http://dev.coding.kz/html5sortable/examples/long-list.html
and there scrolling working without this function (cursorScroll).`

Scrolling on this site works for me in current Chrome (but kind of awkward) and Internet Explorer, but not in Firefox. With the old version of html5sortable from Ali Farhadi I used dndPageScroll (https://github.com/martindrapeau/jQueryDndPageScroll) which worked nicely in all browsers. Unfortunately it does not work with the current html5sortable.

dndPageScroll acts on dragstart, but there's no reaction when in use with the current version of html5sortable. Do you have any idea why dndPageScroll does not catch the dragstart event?

**Comment by lukasoppermann** [comment]
It could be that we swallow the `dragstart` https://github.com/lukasoppermann/html5sortable/blob/master/src/html.sortable.js#L546. maybe you can create a fork and try if changing this helps and if it has any other negative consequences? If not feel free to send in a PR.

Anyway, did you try this version? https://lukasoppermann.github.io/html5sortable/index.html

I actually have no trouble scrolling in chrome or firefox (on mac though).

**Comment by opfertunes** [comment]
I'm seeing this issue but only in Firefox on Linux desktops (I've tried Mint and Ubuntu).

**Comment by lukasoppermann** [comment]
Okay, I can not test this. Do you have any solution for the issue?

**Comment by opfertunes** [comment]
I don't offhand.  I am curious though, will play with it some more.  I guess one could check in the dragover event if near the visible top/bottom of container and scroll if needed.  Might be strange on browsers that currently do the right thing though.

I do have a possible PR, I made it possible to pass options.placeholder and options.dragImage as funcs.

crossbrowsertesting.com has Ubuntu desktop, FYI

**Comment by lukasoppermann** [comment]
Okay, looking forward to seeing what you come up with.

The PR you mention is not related to this issue though, correct? If you have the code already written, please submit it as a PR so we can discuss & merge it, thanks. 👍

**Comment by opfertunes** [comment]
Correct, unrelated...  I needed more control over those things in our application.

**Comment by lukasoppermann** [comment]
Okay, looking forward to your PR

**Comment by n1ckbren** [comment]
Try to use this. It's works for me (tested in Safari and Chrome). 
```
 body {
   overflow-y: scroll;
 }
```

**Comment by nicojerome** [comment]
I solved this by adding an auto-scroll if the mouse cursor moves close to (or over) the top/bottom edge of the list while sorting. My list is a scrollable container (overflow-y: scroll) in my case:

```javascript
sortable(container)

// Add Auto Scroll

var isScrolling;
var scrollSpeed = 10; // Adjust scroll speed as needed
var THRESHOLD = 20; // Adjust threshold distance as needed

function startScroll(container, direction) {
    if (isScrolling) return;

    isScrolling = setInterval(function() {
        if (direction === 'up') {
            container.scrollTop -= scrollSpeed;
        } else if (direction === 'down') {
            container.scrollTop += scrollSpeed;
        }
    }, 20); // Adjust the interval as needed
}

function stopScroll() {
    clearInterval(isScrolling);
    isScrolling = undefined
}

function autoScroll(e) {
    var rect = container.getBoundingClientRect();
    var topDistance = e.clientY - rect.top;
    var bottomDistance = rect.bottom - e.clientY;

    if (topDistance < THRESHOLD) {
        startScroll(container, 'up');
    } else if (bottomDistance < THRESHOLD) {
        startScroll(container, 'down');
    } else {
        if (isScrolling) stopScroll()
    }
}

sortable(container)[0].addEventListener('sortstart', function(e) {
    window.addEventListener('drag', autoScroll);
});

sortable(container)[0].addEventListener('sortstop', function(e) {
    window.removeEventListener('drag', autoScroll);
});
```
