### ISSUE TITLE
HTML5 Table Ajax Sample - does not have the add row or table

### ISSUE THREAD

**Issue by patagoniahiker** [lukasoppermann/html5sortable#186]
Hello, I really like this plugin and would like to try it. 

Looking in the documentation I do not see options for ADD, and Submit (i.e. or on AJAX POST of the new sort order)

Can you please include/provide guidance in the sample for the HTML5 version (non-angular), on how to
- Add a _New Table Row with editable items_
- Collecting the new sort order and form Submit/POST the result to the server - via AJAX

**Comment by lukasoppermann** [comment]
Hey @patagoniahiker,

there is no specific method to add an item. Just add it using javascript and reinit the sortable after adding the item. (If you do not reinit, it will not be draggable).

Currently serialising is not included either. You can use any js serializer. If you want to write one yourself and need some inspiration, you ca check out this branch: https://github.com/lukasoppermann/html5sortable/tree/serializing
