### ISSUE TITLE
can't drop to other <ul>'s last  position

### ISSUE THREAD

**Issue by shejuly** [lukasoppermann/html5sortable#193]
there are two ul ,both of them has some li . I drop ul1's li to the ul2 , Just like the pic . The first time it can not show the placeholder in the ul2's last position. the only way to put it in the last position is: my mouse touch the top of the ul2‘s last li,when the placeholder is show in the penult of the ul2,move down the mouse pointer .

hope to fix it, thank you !

![pic](http://7fvhlq.com1.z0.glb.clouddn.com/1.png)

**Comment by lukasoppermann** [comment]
Please add your code to jsfiddle or codepen, so I can see the problem.

**Comment by shejuly** [comment]
sorry , I use the Jquery UI 's sortable instead. but thank you all the same！
