### ISSUE TITLE
draggingClass not work

### ISSUE THREAD

**Issue by shejuly** [lukasoppermann/html5sortable#194]
options = $.extend({
    ……
    draggingClass: 'sortable-dragging',
  }, options);

in the src html.sortable.src.js I saw the parameter ’draggingClass‘ , I guess it can control the style of the draggingLi . but it seem's not work . hope to fix it ,thanks.

**Comment by lukasoppermann** [comment]
Hey, can you please put your code on jsfiddle or codepen?

It should work fine of you do it like you showed.

```
$('.js-sortable').sortable({
  draggingClass: 'your-class'
});
```

Of course, it might depend on the way you implement it.

**Comment by lukasoppermann** [comment]
@shejuly since you are using a different tool now and it worked in my test, I will close this.
