### ISSUE TITLE
HTML5 Sortable is not working in iPad.

### ISSUE THREAD

**Issue by jeysinghanbu** [lukasoppermann/html5sortable#196]
I tested the Sortable connected list in my iPad, that is not woring whereas same code working fine in Desktop or Laptop.So I tried with [jQuery UI Touch Punch](http://touchpunch.furf.com/) still no luck.
Is there any other Possibilities to achieve this?

**Comment by lukasoppermann** [comment]
This is not supported. On touch devices clicks are canceled when dragged, so there would need to be a work around for this. If you want to add it, feel free to send a PR.

**Comment by medslt** [comment]
@jeysinghanbu hello,
Did you find a solution to use it in iPad?

**Comment by jeysinghanbu** [comment]
@medslt  Hi,
              [jQuery UI touch punch](http://touchpunch.furf.com/) is working fine in iPad and iPhone. I made some mistake with jQuery id selector. Did you try  [jQuery UI touch punch](http://touchpunch.furf.com/) ?

**Comment by medslt** [comment]
@jeysinghanbu Hi,
I didn't try jQuery Ui touch punch but I used https://github.com/RubaXa/Sortable/ it is working fine in iPad and Mobile also. Thank you for your replay.
