### ISSUE TITLE
Possible to work with mobile?

### ISSUE THREAD

**Issue by filipe-nunes** [lukasoppermann/html5sortable#203]
I have a cordova project built for iOS and Android. The plugin works perfectly in my desktop, but it doesn't do anything on the device. I suppose it's the events/native html5 drag drop stuff that don't apply on mobile. Is there anyway this could work on mobile?

**Comment by amhoho** [comment]
same q

**Comment by ProtocolNebula** [comment]
I tested the latest version directly in browser (not through cordova) and it works fine, you must press the item for 1 or 2 seconds before start dragging,
I don't know if it works too in cordova.

**EDIT:** I tried to put in my web and it seems to conflict with something ONLY in mobile (or git has a bug that is not present in demo page)

**Comment by lukasoppermann** [comment]
Most mobile devices do not listen to the "drag" events so this would need to be implemented using the "touch" events. I am open to a PR for this.
