### ISSUE TITLE
Dynamically adjust height of placeholder

### ISSUE THREAD

**Issue by mirraj2** [lukasoppermann/html5sortable#205]
I want the height of the placeholder to be equal to the height of the element that the user has started to drag.

The following did not work.

```
 s.addEventListener("sortstart", function(e) {
    var height = $(e.detail.item).height();
    $(".placeholder").css("height", height + "px");
  });
```

I think because the placeholder is not yet in the DOM. Is there some other way to access the placeholder object?

**Comment by lukasoppermann** [comment]
The problem is more likely that the placeholder already exists. The placeholder is just a copy of the **.placeholder** element, so you can not edit it afterwards.

Did you try the **forcePlaceholderSize** option?

**Comment by jbg77** [comment]
Hello the solution I made: 

```
sortable(sortableClass)[i].addEventListener('sortstart', function(e) {
        var style = $('<style>li.sortable-placeholder { height:'+ e.detail.item.offsetHeight + 'px; </style>');
        $('html > head').append(style);
});
```
