### ISSUE TITLE
How can I adjust my "Tasks" in-line horizontally ?

### ISSUE THREAD

**Issue by heliojsjr** [lukasoppermann/html5sortable#209]
I'm using Html5Sortable to organize some tasks. Everything is working good. I'm using Ruby on Rails and when I move the tasks up or down(vertically), my database is automatically updated.
Now, I wanna display the tasks horizontally (in-line) and move the task right or left.
I have no ideia how to change this.

I appreciate If some one can help me to do this.

**Comment by lukasoppermann** [comment]
Generally you just have to adjust your css so your tasks are left to right by any means. E.g. you could use flex-box and assign a flex-base or just set all to flex: 1 if you want them all in a row.
