### ISSUE TITLE
0.4.0 and old Firefox Version 33.0.2

### ISSUE THREAD

**Issue by fry2k** [lukasoppermann/html5sortable#210]
Hello,
cause of company policies I have to support Firefox version 33.0.2.
Since you removed jQuery with 0.4.0 html5sortable isn't working any more because the Element.matches is undefined.
Firefox 33.0.2 uses mozMatchesSelector.
I fixed it here https://github.com/fry2k/html5sortable/commit/fdd6dd1f3fff6ba3908a5a3a5313582478df877d
I wasn't able to run "npm test" or "npm run test-plugin" successfully at my local copy.

**Comment by lukasoppermann** [comment]
Hey @fry2k,

thank you for your contribution. I added the suggested code and publish 0.4.1. Let me know if it works for you.

**Comment by nazar-pc** [comment]
When making it jQuery-free I decided to not support too old browsers. All modern Firefox versions (including ESR) supports `element.matches()`, so IMHO, maintaining prefixes compatibility for old browsers is up to downstream users.

**Comment by fry2k** [comment]
@lukasoppermann 
Thank you verry much for your quick update. 0.4.1 works for me with ff 33

@nazar-pc 
I understand and I'm with you removing browser prefixes if possible and cleanup the code.
If you remove this stuff it would be great if we could pass a filter function with an optional parameter or disable the filtering. Maybe if options.items is already an array we don't need a filter? Sure I could fork the repository and hack the stuff by my own but looking forward to updates it would be awesome if I could pass my hacks through a configuration.
btw ff 33 is from late 2014, 2 years old. sure the current version is 48 but at my company I have no influence to upgrade :/
