### ISSUE TITLE
Link to GitHub broken

### ISSUE THREAD

**Issue by UweKeim** [lukasoppermann/html5sortable#211]
On [this page](http://lukasoppermann.github.io/html5sortable/examples/index.html) the "Fork on GitHub" link is broken to me.

I'm using Chrome 54 on Windows 10 (both 64 bit).

In addition, I'm getting a JavaScript error:

> Uncaught ReferenceError: module is not defined
>     at http://lukasoppermann.github.io/html5sortable/src/html.sortable.src.js:432:1

**Comment by lukasoppermann** [comment]
Fixed, thanks.

The error is "expected" as otherwise it adds an unneeded overhead.
