### ISSUE TITLE
about the statement "else if" does not exist in javascript

### ISSUE THREAD

**Issue by r3wt** [lukasoppermann/html5sortable#213]
Yes it does. But 99% of the time you should use a switch (thoug not always, there are valid reasons to use else if)

there is no `elseif` but there is definitely `else if`

**Comment by lukasoppermann** [comment]
Yes, you can write this, but it is not the same.

Basically what you write is this:

``` javascript
if(condition){

}else{
   if(condition){

   }
}
```

This is not the same as an `elseif` that is known from other languages. See: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/if...else

**Comment by r3wt** [comment]
are you fucking retarded? `else if` is a legitimate conditional operator in javascript.

``` js
function isVoidBergRetarded(){
  var you = 'just ignorant';

  if(you == 'legitimately retarded'){
      console.log('you are legitimately retarded, no offense.');
  }
  else if(you =='just ignorant'){
       console.log('you are just ignorant, unfortunately.')
  }else{
       console.log('you are neither retarded or ignorant. try harder');
  }
}
```

https://jsfiddle.net/r1gn6owe/1/

I am sharing this with the author of the language, brendan eich. your ignorance is completey uncalled for.

**Comment by lukasoppermann** [comment]
There is no call for being insulting, this is not reddit.

If you would have read the post above you would see that there is of course an `else if` condition, which I never denied, but it is not the same as `elseif` an can lead to unwanted side effects.

If you want to contribute to projects in the future, please watch your language.

**Comment by r3wt** [comment]
It's the exact same thing as `elseif` just with a space. See the jsfiddle

**Comment by BrendanEich** [comment]
See https://twitter.com/BrendanEich/status/774038782467121152. @lukasoppermann am I correct in deducing that you were thinking of dangling else being permitted by JS (after Java, C++, C)?

**Comment by lukasoppermann** [comment]
@BrendanEich yes, I actually thought that was possible and could be leading to problems. Hmm, I will adjust the readme, thanks for clarifying.
