### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by mczuchnowski** [lukasoppermann/html5sortable#215]
So ever since I've added html5sortable to my project, it works very well, but it always throws this error in the console:

`Uncaught ReferenceError: module is not defined`

and this relates to this line:

module.exports = sortable;

Any ideas?

**Comment by lukasoppermann** [comment]
Yes. Are you including the file from the `src` folder by any chance?

**Comment by mczuchnowski** [comment]
Yes, I do (that's what one of the tutorials told me to do ;) ). It was a mistake, wasn't it?

**Comment by lukasoppermann** [comment]
Which tutorial? Yes, you need to use the file form `dist`. It should probably me made more clear in the readme.

**Comment by lukasoppermann** [comment]
Updated readme: https://github.com/voidberg/html5sortable/commit/077338209663cd5c7916c1a0c694d7776e788903
