### ISSUE TITLE
Issues with destroy and reinit

### ISSUE THREAD

**Issue by doctadre** [lukasoppermann/html5sortable#220]
If you add a new container and call sortable($(selecotor)) it doesn't add the new container and thus you cannot drop products in it (im working with connected containers).

If you call destroy on a sort and then reinitialize it, the sortStart and sortStop event listeners never get removed. So for each time i reinitialize the sort to pick up new containers, i get a new listener attached

**Comment by lukasoppermann** [comment]
Hey @doctadre, could you identify the problem and create a PR to address this issue? Thanks.

**Comment by lukasoppermann** [comment]
Closed due to inactivity
