### ISSUE TITLE
Transfer to Lukas

### ISSUE THREAD

**Issue by voidberg** [lukasoppermann/html5sortable#226]
Not sure what the best way to do this is but we can try something like:

* Lukas creates a fork and detaches it (by contacting GitHub support) or creates a new repo.
* I wipe this one and leave a README with a note that the repo has moved.

@lukasoppermann sounds good?

**Comment by lukasoppermann** [comment]
Hey @voidberg, I think it would be easiest to transfer ownership via the "settings menu". This way all issues, history, connections, etc. stay as they are.

<img width="778" alt="screen shot 2017-02-24 at 11 47 28" src="https://cloud.githubusercontent.com/assets/813754/23300699/0e0aad5c-fa87-11e6-922e-19c4f3cab007.png">

**Comment by voidberg** [comment]
Forgot about that option. :)

**Comment by voidberg** [comment]
@lukasoppermann You first need to delete your fork. It's not letting me transfer as `lukasoppermann/html5sortable already exists`.

**Comment by lukasoppermann** [comment]
Forgot about this, sorry. 😄 

Gone now, should be working. 👍

**Comment by voidberg** [comment]
Now it's complaining that `lukasoppermann already has a repository in the voidberg/html5sortable network`. I removed you from the project but that was not it. Any ideas?

**Comment by lukasoppermann** [comment]
Hmm, I had another fork, but with a different name. Maybe that is the issue? I just deleted it. Could you try again please?

**Comment by voidberg** [comment]
That did it. :)

**Comment by lukasoppermann** [comment]
Awesome, this worked. 👍  Thanks.
