### ISSUE TITLE
Dropping outside the list has no effect

### ISSUE THREAD

**Issue by eskimoblood** [lukasoppermann/html5sortable#23]
When I start dragging the placeholder is set to the position where the dragged item will go when dropping. But when I release the mouse outside the list, the item moves back to its initial position. This is very confusing for the user as he excepts the item to go to where the placeholder is. 

So either the the item moves to last position of the placeholder or the placeholder moves back to the initial position of the item, when the item is dragged outside the list.

**Comment by fiznool** [comment]
+1 for this too. It's very confusing the first time this is witnessed.

**Comment by lukasoppermann** [comment]
This is intended behaviour, as a drop outside a list is a cancel event. However I agree that as an enhancement the placeholder could be moved back to the original position when moving outside. If somebody is interested in adding this features, please open a PR.
