### ISSUE TITLE
Handle not working at all on IE or Edge.

### ISSUE THREAD

**Issue by benoit-outsourcify** [lukasoppermann/html5sortable#233]
You can check the examples on :
https://lukasoppermann.github.io/html5sortable/index.html

It's actually not working at all on IE 11, just not working with handles on Edge.

SCRIPT5007: Unable to get property 'parentElement' of undefined or null reference
html.sortable.js (687,7)

**Comment by lukasoppermann** [comment]
Hey @benoit-outsourcify, this seems related to #147. I don't have any IE to test it. Would you be able to submit a PR?

**Comment by lukasoppermann** [comment]
Should be fixed, please reopen with detailed test case or bugfix.
