### ISSUE TITLE
JS errors when dragging disabled elements.

### ISSUE THREAD

**Issue by adamvoigt** [lukasoppermann/html5sortable#238]
Hi, first thanks so much for this library, it's really useful. I noticed an issue that's causing the library to throw JS errors if the user does something unexpected so I wanted to let you know about it. If you select the text of a disabled element and then proceed to drag the text, every pixel the mouse moves over top of the sortable list throws a JS error. I know no one should ever do this, but as all of us developers know, users are great at doing things they're not supposed to do. :smiley:

Steps to reproduce:

1. Open JS console.
2. Go to the [example page](https://lukasoppermann.github.io/html5sortable/index.html).
3. Scroll down to the section marked "Exclude items & nested list".
4. Select the text "disabled 3".
5. Click the selected text and drag it around the list.

Result:

Errors similar to this:
Uncaught TypeError: Cannot read property 'parentElement' of null
    at HTMLUListElement.C (html.sortable.js:695)

**Comment by lukasoppermann** [comment]
I am on vacation until end of next week. I think it is related to #147 if you can send a fix via PR that would be great and very much appreciated. 😀

**Comment by yue-fei** [comment]
line 694

```
var onDragOverEnter = function (e) {
    if (!dragging) {
        return
    }
    ...
}
```

**Comment by lukasoppermann** [comment]
@yue-fei good one 👍  should be fixed now. @adamvoigt please comment if it persists once you update to the new version.
