### ISSUE TITLE
event on drag

### ISSUE THREAD

**Issue by gvorbeck** [lukasoppermann/html5sortable#24]
I would like to be able to have a list become visible when an item is being dragged. Currently, .click() and the like only fire once I release the mouse button. jQuery UI has the ability to target this, is there a way with html5sortable?

**Comment by gvorbeck** [comment]
Unless that functionality is already built in (and my reading of javascript is a little spotty), I'm going with this: https://stackoverflow.com/questions/4127118/can-you-detect-dragging-in-jquery

**Comment by lukasoppermann** [comment]
Well you have the `sortstart` event which is fired when an item is dragged and a `sortupdate` when the order changes and the item is dropped.
