### ISSUE TITLE
Copy option

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#265]
Allow for items to be `copied` (cloned) instead of moved to a connected list.

**Comment by WoodyAlmeida** [comment]
Was looking exactly for this, unfortunately I don't have enough experience in JS to do it. Anybody knows if someone is working on this?

**Comment by lukasoppermann** [comment]
Hey @WoodyAlmeida, sadly I don't think so. I know you said you don't have that much js experience, but if you would like to send in a PR I can help you with it. Basically you would need to allow for a new option `copy: true` passed into the sortable function. 

You would need to check it when dragging and only remove the old item, if copy is set to false.

Best would be to instead of checking the copy option directly, creating a function `isCopyActive` which returns `opts.copy` for now but could later be enhanced to check for keyboard shortcuts.

**Comment by mfriesen** [comment]
I have added this copy feature. I will be creating a pull request soon.

**Comment by lukasoppermann** [comment]
Great initiative @mfriesen, feel free to also send a WIP PR so we can discuss stuff early on.

**Comment by mfriesen** [comment]
@lukasoppermann The change doesn't seem very large.
1) In the 'dragstart' event where "dragging = this". 
I changed it (if the "copy:true" option is set) to return this.cloneNode(true).

One issue I ran into was if you have an unsuccessful drop (IE: You drop it on a list where _listsConnected returns false).  The copied element needs to be removed from the DOM in the 'dragend' event.

So, I added "_data(dragging, '_dropped', 'true')" into the 'drop' event so I know if the element was successfully dropped in the 'dragend' event. That way I can remove the element if the drop failed.

any suggestions?

**Comment by lukasoppermann** [comment]
@mfriesen hey, can you send a PR? It sounds good, but I find it easier to judge if I see the code. 😁 

Also please try to add some tests (you can send a PR first without any tests though and add them later) to verify: cloning works, deleting works, and drop only works for allowed items and the that sortupdate event fires correctly and the data in it makes somewhat sense. 👍  thank you.

**Comment by lukasoppermann** [comment]
Hey @mfriesen couldn't you actually use the `copy` keyword in the `dropEffect` instead of cloning the node? https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect

**Comment by mfriesen** [comment]
I believe that only changes the visual cursor. But I believe the cloning is still required.
IE: I was looking at http://www.useragentman.com/tests/dragAndDrop/05-dataTransfer.html as an example. It looks like cloning is still used.
Do you want the cursor to change to the Plus cursor?

**Comment by lukasoppermann** [comment]
Hey @mfriesen, I just tried it out and it seems like you are right, this seems stupid. 

Anyway, generally a change in course seems good to me from a UX perspective, as this indicates to the user what will happen.

Anyway, what happens if I move a copyable item into its own parent list? What would you expect?
