### ISSUE TITLE
thoughts on touch support?

### ISSUE THREAD

**Issue by stefanpenner** [lukasoppermann/html5sortable#27]

**Comment by voidberg** [comment]
I need this as well so it's one of the priorities.

**Comment by eirikhm** [comment]
+1. Any ideas on what's needed to make this work? I've not looked into it yet, but will probably fork and implement.

Edit: Well, see http://caniuse.com/#feat=dragndrop

**Comment by fiznool** [comment]
No idea if this is of any use, but the competing [Sortable](https://github.com/RubaXa/Sortable) library has support for touch events, so might help to steer in the right direction.

**Comment by lukasoppermann** [comment]
Don't think is is gonna happen any time soon, looking at the browser support mentioned by @eirikhm.
