### ISSUE TITLE
Is it possible to change the ghost image when dragging of the element occurs

### ISSUE THREAD

**Issue by mattduple** [lukasoppermann/html5sortable#271]
There seams to be a ghost image on drag which can't be changed is it possible to change this ghost image to an html element?

**Comment by lukasoppermann** [comment]
Can you please provide a test case (e.g. js fiddle) and tell me the browser, version and OS?

Currently the ghost can not be change, however it should be an easy fix. All you need to do is to allow the user to overwrite `_makeGhost` via the `options` passed to the sortable. 

A PR would be very welcome.

**Comment by llmziad** [comment]
@lukasoppermann Is this still open?

I see those lines in `html5sortable.ts:347`:
```
      // add transparent clone or other ghost to cursor
      setDragImage(e, dragItem, options.customDragImage)
```

It looks like it was already implemented to me. If not, would love to take it if you can clear up what needs to be done.

**Comment by lukasoppermann** [comment]
@ZiadAliKhalifa I think it is possible if you create a custom function and assign it to `options.customDragImage`.
To solve this I think it would be good if you could test it e.g. on the docs html document or jsfiddle and document how to do it in the readme afterwards. If you could send a PR with this, that would be very helpful. 👍

**Comment by varunKT001** [comment]
@lukasoppermann I would love to work on this issue; please assign it to me 😄

**Comment by varunKT001** [comment]
@lukasoppermann 

This issue seems to be already fixed. We pass a function to the `customDragImage` option to accomplish this. One thing we can do is simplify the process. Instead of providing a function, we can pass the query string, such as `.drag-image`, to the `customDragImage` option. We can use the query string to get the element and create a function.

```js
sortable('.sortable', {
  customDragImage: '.drag-image',
});
```

Please give your opinion on this, and I'll start working on this.

**Comment by lukasoppermann** [comment]
> @lukasoppermann
> 
> This issue seems to be already fixed. We pass a function to the `customDragImage` option to accomplish this. One thing we can do is simplify the process. Instead of providing a function, we can pass the query string, such as `.drag-image`, to the `customDragImage` option. We can use the query string to get the element and create a function.
> 
> ```js
> sortable('.sortable', {
>   customDragImage: '.drag-image',
> });
> ```
> 
> Please give your opinion on this, and I'll start working on this.

Hey, I think we could allow users to pass either a function or a selector string.
If they pass a selector string we create the function for them, if they add a function we run the function (people may want to do something more crazy with it.)

**Comment by varunKT001** [comment]
@lukasoppermann Sounds good. I'll make a PR soon 👍

**Comment by yuki-katayama** [comment]
@lukasoppermann @varunKT001 
Has this issue been addressed yet?
If you haven't already, I'd like to take care of it.

**Comment by yuki-katayama** [comment]
This issue has been resolved and will be closed.
