### ISSUE TITLE
long drags don't scroll page

### ISSUE THREAD

**Issue by kaeverens** [lukasoppermann/html5sortable#273]
if I have a list that is longer than the viewport, and I try dragging from the top to the bottom, the page does not scroll so I have to do it in stages

**Comment by lukasoppermann** [comment]
Hey @kaeverens, does it also not work here: https://lukasoppermann.github.io/html5sortable/index.html ?

Which browser / OS are you using? I am on mac with chrome and it works fine.

**Comment by kaeverens** [comment]
Chrome on Linux.

All of the examples on that page are quite short. If you shrink your browser down you'll see the issue.

1. Shrink the browser
2. Scroll so that only the top two items of the first demo (Sortable List) are visible at the bottom of the page
3. Try to drag the top item to the bottom of the list

**Comment by lukasoppermann** [comment]
Yes, I tried it with the list half visible only, but when I move the item down it scrolls fine. I don't have Linux so I can not test it. However I would appreciate a PR to fix this, if there is a way to fix it.

**Comment by kaeverens** [comment]
I'll see if I can fix it. It might be a difference between Linux and Mac

**Comment by lukasoppermann** [comment]
I guess it would be different. As far as I am aware we did not actually build this in, as it is just browser behaviour to scroll when something is dragged to the bottom at least on mac. If you can fix it, that would be awesome. 👍

**Comment by kaeverens** [comment]
I discovered the issue. it's not an issue in your code. it appears to be a browser issue. it appears to be that if the top or bottom of the element you are scrolling in is covered by a position:fixed element (like a floating header/footer), then the browser's page scroll doesn't trigger.

**Comment by kaeverens** [comment]
actually - I'm sorry, the issue I found solves the problem in my own case, but it still exists on your demo page. I can't spend more time on this at the moment, though.

...and I just checked and it's working on your demo page as well. *sigh*

heisenbug...

**Comment by lukasoppermann** [comment]
Thanks for looking into it and reporting back. 👍
