### ISSUE TITLE
Keep drag within container?

### ISSUE THREAD

**Issue by jam3sn** [lukasoppermann/html5sortable#276]
Hi there, was hoping to find out if there is a way to keep my dragable item within its container, essentially the equivalent to this: http://api.jqueryui.com/sortable/#option-containment? I couldn't see anything in the documentation, apologies if I missed it.

Thanks,
James :)

**Comment by lukasoppermann** [comment]
Hey @jam3sn,

so you want the item to stop at the boundary of the parent? This is currently not possible. 

I would love to accept a PR though, if you send one in.
