### ISSUE TITLE
horizontal sorting

### ISSUE THREAD

**Issue by xguntis** [lukasoppermann/html5sortable#280]
Hi, I am trying to make sortable items horizontally. Does this plugin support it? i get unexpected results https://codepen.io/xguntis/pen/qXwXqW?editors=1111

**Comment by lukasoppermann** [comment]
Hey, I am not at a computer but I will check it out later. The support is somewhat buggy so if you could provide some improvements it would be greatly appreciated.

**Comment by lukasoppermann** [comment]
Hey @xguntis can you elaborate on what you mean by "unexpected results". Thanks.

**Comment by xguntis** [comment]
After some experimenting i found the solution by styling .sortable-placeholder. If you remove the float from it then you will see what was the problem before.

```
.sortable-placeholder {
    height: 50px;
    width: 45px;
    border: 1px solid green;
    float: left; /*this fixed the problem*/
}

.inline {
  float: left;
  width: 50px;
}
```

**Comment by lukasoppermann** [comment]
Perfect.
