### ISSUE TITLE
oldindex retains original index after sortupdate with multiple moves.

### ISSUE THREAD

**Issue by merccat** [lukasoppermann/html5sortable#281]
Greetings,

e.detail.oldindex seems to retain the original index of the item that was moved if an item is moved more than once within a list.  Note that e.detail.oldElementIndex does appear to be updated with each move.  

I am working with items in a single list.  Observed this behavior in Firefox and Chrome, have not tried others.

Not sure if this is by design as I could see it being useful referring back to what the lists original order was but it does not sound like it from the documentation which simply states that it contains the old index of the dragged element (considering only list items).

If people do want the original order retained, perhaps an originalIndex property?

**Comment by lukasoppermann** [comment]
Hey, thanks. This sounds like a bug to me. Could you send a PR to fix this?
