### ISSUE TITLE
sortupdate not firing

### ISSUE THREAD

**Issue by pppws** [lukasoppermann/html5sortable#283]
hey there,

i included your plugin and i can drag and drop my stuff. but somehow i can't make the sortupdate event work. 
this is my html:
```
<ul class="professions-container sortable" data-sortable-id="1" aria-dropeffect="move">
    <li class="row item" data-item-sortable-id="1" draggable="true" role="option" aria-grabbed="false">
        <input class="profession" type="text" name="profession_1" value="first entry">
        <div class="check"><input type="checkbox" id="pcurrent_1" name="pcurrent_1"><label for="pcurrent_1"></label></div>
    </li>
    <li class="row item" data-item-sortable-id="1" draggable="true" role="option" aria-grabbed="false" style="">
        <input class="profession" type="text" name="profession_2" value="second entry">
        <div class="check"><input type="checkbox" id="pcurrent_2" name="pcurrent_2"><label for="pcurrent_3"></label></div>
    </li>
    <li class="row item" data-item-sortable-id="1" draggable="true" role="option" aria-grabbed="false" style="">
        <input class="profession" type="text" name="profession_3" value="third entry">
        <div class="check"><input type="checkbox" id="pcurrent_3" name="pcurrent_3"><label for="pcurrent_3"></label></div>
    </li>
</ul>
```

and i'm using:
```
sortable('.sortable')[0].addEventListener('sortupdate', function(e) {
           console.log('log');
});
```

which returns no console message.
basically i'm trying to change the names of the input and checkbox fields.

thanks for any help :)

**Comment by pppws** [comment]
update: nevermind, i found my mistake for the update-status, still figureing how to update the input fields.

:)

**Comment by lukasoppermann** [comment]
Closing since you got the sortupdate working.

**Comment by bosskovic** [comment]
@pppws what was the problem (I can't see any in your code snippet)? I have an issue similar to the one you described - d&d works fine, adding listeners produces no errors in the console, but also none seem to be fired (I tried sortupdate, sortstart, sortend...)

**Comment by bosskovic** [comment]
For anyone coming here in future with the same problem, when adding the markup, check the instructions on the readme page. I did the same thing as pppws, I copied and adapted the markup from the demo, which includes attributes dynamically added by sortable. In short, `data-sortable-id`, `aria-dropeffect`, `data-item-sortable-id`, `draggable`, `role` and `aria-grabbed` should not be manually added.
