### ISSUE TITLE
how to add a fixed label column

### ISSUE THREAD

**Issue by avidh** [lukasoppermann/html5sortable#284]
Hi,
I want to have 10 items in the sortable list but would have to display a fixed rank number 1 through 10 in front of the list (sort of like fixed column) so that when the user is dragging an item, they can see what the new rank is before dropping the item.

Is there a way to achieve this?
Thanks in advance.

**Comment by lukasoppermann** [comment]
Well, you need to do this outside of the sortable. You could for e.g. have two lists next to each other, one being a sortable, the other holding the numbers.

Is this what you are looking for?

**Comment by avidh** [comment]
Sort of (pun not-intended) 
Is there a way to use the Sortable Table example except fix the first column that holds the ranking numbers?

**Comment by lukasoppermann** [comment]
No, I am pretty sure that does not work. If you want to send a PR for this, it would be very welcome.

**Comment by avidh** [comment]
Looks like the sortable/draggable attributes are set at `<tr>` level so maybe this is not that straight forward or not possible...

I'm going to see if I can work with two lists right next to each other (touching), making one sortable and the other not to make it look like a table with two columns...
Thank you.

**Comment by lukasoppermann** [comment]
Sure, sorry I could not help more.
