### ISSUE TITLE
Doesn't work in Firefox 56 & 57 on Linux

### ISSUE THREAD

**Issue by al3xnag** [lukasoppermann/html5sortable#285]
![html5sortable_ff](https://user-images.githubusercontent.com/4932134/32480760-29ba2d62-c3b2-11e7-82d4-0d9b9637a679.gif)

Firefox 57.0b12 (64-bit) and 56.0.2 (64-bit).
Console is empty, no errors.
Linux 4.9.59-1-MANJARO x86_64

**Comment by lukasoppermann** [comment]
Hey, sadly I have no linux OS available to test. If you can find any way o fix this, please let me know or send a PR. I would really appreciate your help here, as I can not test it.

It looks like maybe  the dnd api is buggy there? As the dragging seems to work fine and it only has a hard time recognizing the drop.

**Comment by lukasoppermann** [comment]
Ping @nag5000

**Comment by al3xnag** [comment]
@lukasoppermann 
I can't promise that I will be able to find some time for it in the near future. Anyway, If I find a problem or solve it, I'll let you know.

Just tested on FF 58.0b5 (64-bit) on linux - same behavior.

Also I can suggest you to test it using vmware or virtualbox, with an image from http://www.osboxes.org (e.g. http://www.osboxes.org/manjaro/#manjaro-0_8_13-vmware).

**Comment by m-grey** [comment]
@lukasoppermann @nag5000 
You can add FF 59.0a1 to the list of FF versions that this doesn't work in.

Running on Fedora 24, a fresh install of FF 59.0a1 without addons displays the behavior seen in the animation above.

Any timeline on a fix?

**Comment by lukasoppermann** [comment]
Hey,

it might be this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=804036 ?

react dnd seems to have a similar issue: https://github.com/react-dnd/react-dnd/issues/778 can you please try if you have the same issue here: https://react-dnd.github.io/react-dnd/examples-sortable-simple.html 

Thanks

**Comment by al3xnag** [comment]
Yes, similar issue (FF 58.0b5, Linux Manjaro):
![examples-sortable-simple](https://user-images.githubusercontent.com/4932134/33112726-7bb364c4-cf76-11e7-851a-798f0e36ef9e.gif)

**Comment by m-grey** [comment]
The React example does pose problems for me on FF Nightly, but it is not as severe as the problems with sortable. 

In the react example, I can rearrange the draggable items, but this behavior stops responding after ~ 0.5s. 

In sortable, I cannot rearrange the draggable items at all, just like in the animation.

**Comment by lukasoppermann** [comment]
So it is save to assume it is an issue with firefox at this point, right? It might be that the event is fired later in the react example which is why it works in the beginning, but this does not solve the issue either.

**Comment by m-grey** [comment]
There are no reports on bugzilla relating to this issue. Given that the issue is persistent across 4 versions of FF, I think more testing must be done to confirm that it is FF and not a bug shared by two plugins.

@lukasoppermann could you please run some tests on a Linux VM? Your knowledge of the plugin will offer the best opportunity for a solution.

**Comment by gyunaev** [comment]
I can confirm that this issue also reproduced on Firefox 52.5.0 on Linux (which is ESR version).

And I can also confirm that the module from https://rubaxa.github.io/Sortable/ works fine.

**Comment by lukasoppermann** [comment]
Hey, I currently do not have the time to work on this issue, especially since it is an unknown OS for me. 

I would really appreciate of one of you could figure out why rubaxa's version works and send a PR I am happy to assist with the PR should there be any issues. Thanks.

**Comment by lukasoppermann** [comment]
Duplicate of #277
