### ISSUE TITLE
Incorrect hover with bootstrap

### ISSUE THREAD

**Issue by m0nhawk** [lukasoppermann/html5sortable#287]
I was trying to make a drag'n'drop with Bootstrap styles, but the wrong item is being hovered.

[JSFiddle](https://jsfiddle.net/k10aumrz/)

**Comment by lukasoppermann** [comment]
I think you are referring to the `:active` state, correct? As the hover is working fine for me.

**Comment by m0nhawk** [comment]
For example, I drag the first item to the bottom and the second item is being highlighted (I'm not sure, if it's hover or active). But it shouldn't be highlighted like this.

![default](https://user-images.githubusercontent.com/8220926/33367455-51f1a1e2-d4f7-11e7-9af3-81709e678695.png)

**Comment by lukasoppermann** [comment]
Its active. This is actually an issue with the combination of using a "li:active" selector and the native drag and drop api. 

If you find out how to solve this (I currently don't know, maybe you can disable active on dragstart or something). Please let me know and send a PR. That would be really awesome.
