### ISSUE TITLE
change class for each <li> after sortupdate

### ISSUE THREAD

**Issue by pppws** [lukasoppermann/html5sortable#288]
hey there,

i'm using your great plug-in and i love the simple implementation of it!

after setting up the basics i'm now trying to update the class for each li (basically class="#newindex#") after i replaced one of them.

when using: 
`    sortable('.sortable')[0].addEventListener('sortupdate', function(e) {

            //console.log(e.detail.index);
            $('li').each(function() {
                console.log(e.detail.index);
            });

        });`

i only get the new index of the dragged item not for each item.

any help is appreciated! thanks

**Comment by lukasoppermann** [comment]
You should be able to just use "newEndList" and "newStartList" from the sortupdate event. https://github.com/lukasoppermann/html5sortable#sortupdate

If you move items within one list only, they are the same. Please reopen if this does not solve your issue.
