### ISSUE TITLE
Link doesn't work without using handle in IE and Edge?

### ISSUE THREAD

**Issue by obiwanwrc** [lukasoppermann/html5sortable#291]
Hi everyone, we have a list of sortable list elements (li) with an image and a link inside (below the image) for deleting the image itself.

If I don't set the handle element everything works fine in Chrome and Firefox, but in IE and Edge the clickable link doesn't fire - apparently the sortable plugin is always fired first. So I specified the handle element as "img", the sortable continues to function correctly on Chrome ad FFX if I grab the image element but in IE11 it doesn't work as expected, the sorting works but the placeholder doesn't work (apparently it seems to not work at all but it sorts eventually) and in Edge the sorting doesn't work at all.

Does anyone knows if there is a problem with IE/Edge using the "handle" option?

**Comment by lukasoppermann** [comment]
Hey,

I know that IE/Edge have some issues with this.
The issue with links is know and should be added to the readme under issues and limitations. 

Can you please try to specify a div or li or span as a handle and verify that it still works.

**Comment by lukasoppermann** [comment]
Hey @obiwanwrc did you have any luck with verifying if it works with a `li` or `div`?

Actually it looks like links should also work: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673539(v=vs.85)

**Comment by lukasoppermann** [comment]
Closed due to inactivity.
