### ISSUE TITLE
How to disable the opacity on drag?

### ISSUE THREAD

**Issue by xy2z** [lukasoppermann/html5sortable#293]
On Farhadi's demo there doesn't seem to be opacity when dragging items. See http://farhadi.ir/projects/html5sortable/

Is there a way to disable this opacity? I've but couldn't find a solution..

**Comment by lukasoppermann** [comment]
This is currently not possible, as this is the default HTML5 Drag & Drop behavior. A custom ghost creation would have to be implemented.
