### ISSUE TITLE
remove globals

### ISSUE THREAD

**Issue by leolems** [lukasoppermann/html5sortable#297]
I was looking for a good nice small lib, unfortunately this uses global vars... which is a pretty big nogo.

**Comment by lukasoppermann** [comment]
Yes (1 global `sortable`, if I am not mistaken), this is necessary for people who do not use some kind of module system.

However feel free to send a PR to allow an additional build which is not a UMD but just a module.

Of course you could also send a PR that changes the src to be es6 module based and add a build step for a UMD, but this would be quite a bit (but good) PR.
