### ISSUE TITLE
Fix Copy Option

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#311]
Hey @mfriesen there is an issue with the copy option:
https://lukasoppermann.github.io/html5sortable/index.html

- [ ] The new items that are added to a sortable are not part of it, so we would need to reinit every time a copy is added to an item. (This is not so good, maybe we could fix this by fixing the general issue: adding new items to a sortable should automatically work, without the reinit: #312)
- [ ] A bug in copy is that when I move a copied item onto an invalid target (and my copy start list has `acceptFrom:false`) the item still goes back to the parent. This could also be seen in a bigger picture so that dropping outside a valid target should cancel the sorting action (similar to when pressing `esc` #313)

**Comment by mfriesen** [comment]
@lukasoppermann I'll take a look at the reinit problem. I should have caught that problem.

For the second part are you saying that once you drop the 'copy' on a valid target the item is pointing to the original parent?

The other thing I just noticed was that the data-item-sortable-id doesn't change when moving items between 2 sortables. Is that ok?

**Comment by lukasoppermann** [comment]
Nice, thank you for looking into it mate.

Concerning your question, to reproduce it in the github demo page:
1. drop any item to the empty list
2. try to drop another item (you will not be able to)
3. release the item 
4. now there are 2 items of this type (e.g. item 2) in the right list.
Is this understandable?

Concerning the ID, I think it is useless. It is only in one place in the code, as far as I can see, so we can probably remove it safely (this needs to be checked though). I think it is a leftover from an old version.

**Comment by lukasoppermann** [comment]
Hey @mfriesen make sure to get a fresh pull of the master branch, quite a lot has changed. 😉

**Comment by mfriesen** [comment]
@lukasoppermann I can't get the test to pass now. Any ideas with the following errors?
1) Testing api
       Initialization
         "before each" hook for "should have a data-opts object":
     TypeError: window.sortable is not a function
      at Context.<anonymous> (test/api.js:32:14)

 16) Testing ghost creation methods
       sets the dataTransfer options correctly (_attachGhost):
     TypeError: Cannot read property '__testing' of undefined
      at Context.<anonymous> (test/ghost.js:50:21)

**Comment by lukasoppermann** [comment]
Hey @mfriesen I will merge the placeholderMap PR some time today. Do you think you can attack this issue when you have time? Because we need this fixed before we can create a release as copy is merged but currently has this bug. Thank you very much.

Ahh, and the IDs have been removed, as you might have seen.

**Comment by mfriesen** [comment]
@lukasoppermann fixing this bug is what I'm trying to do. But in order to do it properly I need to extract break up the code inside of the 
```
sortableElements.forEach(function (sortableElement) {
```
After my pull requests are merged, I will extract the 
```
_on(items, 'drag event .,.', function (e)
```
to their own function. Then I believe I can fix this problem.

**Comment by lukasoppermann** [comment]
Perfect, that is what I thought. Thank you!
