### ISSUE TITLE
Convert to typescript

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#314]
Convert the source file to typescript, which will be compiled in the rollup build step. 
While we currently use `.ts` files, typehinting etc. is not used in the files.

**If you want to help:**
Just start adding typehints to any file that is still missing them or improve the ones that already have them. Feel free to send a PR for files even if only a part of them is converted.

**Comment by 3r3n-n** [comment]
Hi ! 
I see that this is an old issue but if there are still some files that need to be converted to TS, I’d be happy to help.

**Comment by lukasoppermann** [comment]
Hey, thank you, there are two important things concerning typescript:
1. The PR to update fails #745 so this needs to be fixed (I didn't really check out what is the problem yet)
2. The main file with everything that was not extracted to smaller modules yet is not using typings or other typescript features at all and could profit from it: https://github.com/lukasoppermann/html5sortable/blob/master/src/html5sortable.ts

If you want to work on either or both of those issues it would be very great.
You can also extract functionality from the html4sortable.ts into smaller modules where it makes sense and convert this over to typescript. This may be easier and more fun than in the big file.

**Comment by 3r3n-n** [comment]
Great !
I am an OS newbie so I think I would be more comfortable trying the second option :)

**Comment by lukasoppermann** [comment]
Sounds great. Whatever you feel most comfortable with is a good start and very much appreciated. 👍

If you have questions, just send a PR and add a comment with your questions.

**Comment by lukasoppermann** [comment]
Stale
