### ISSUE TITLE
Cannot read property 'parentElement' of undefined when using Ajax post

### ISSUE THREAD

**Issue by ruudmens** [lukasoppermann/html5sortable#328]
I want to submit the sortable data with other form data trough ajax. But somehow I keep getting the parentElement undefined error when I try to send the data. The error seems to be triggered by the Ajax call, but I really don't understand why.

q results in a nice array of the sorted items, so the serialize works.

Code:

    var q = sortable('.survey_question_chapter .survey_questions', 'serialize');
    var f = $('form#createSurvey').serialize();
    
    $.ajax({
      url: '/survey/create',
      type: 'post',
      dataType: 'json',
      data: {form:f,question:q},
      success: function(data) {
        //redirect
      }
    });

Resulting error: in at sortable-min.js:formatted:270

     i([s, M], "drop", function(t) {
                var a;
                g(s, e.parentElement) && (t.preventDefault(),  << ERROR
                t.stopPropagation(),
                r(e, "dropped", "true"),
                a = n.filter(w)[0],
                A(a, e))

**Comment by lukasoppermann** [comment]
Can you try the non-minified version and what kind of error you get? Thanks.

**Comment by ruudmens** [comment]
File is still called -min, but content is replaced with the non-minified version.
Error at line 643:

```
// Handle drop event on sortable & placeholder
      // TODO: REMOVE placeholder?????
      _on([sortableElement, placeholder], 'drop', function (e) {
        var visiblePlaceholder;
        if (!_listsConnected(sortableElement, dragging.parentElement)) {
          return;
        }
```

error in console:
   ```
 Uncaught TypeError: Cannot read property 'parentElement' of undefined
    at sortable-min.js:643
    at o (jquery.js:6)
    at gn (jquery.js:6)
    at gn (jquery.js:6)
    at gn (jquery.js:6)
    at gn (jquery.js:6)
    at gn (jquery.js:6)
    at Object.<anonymous> (jquery.js:6)
    at Function.each (jquery.js:4)
    at gn (jquery.js:6)
```

**Comment by lukasoppermann** [comment]
Okay, thanks. Just making sure, you are running version `0.7.0` correct? 

Is there a chance you copuld upload this code onto jsFiddle or something?

**Comment by ruudmens** [comment]
No version info in the file, but I crapped the latest from the dist folder.

**Comment by lukasoppermann** [comment]
Did you download the master? Or from the releases? You should use a version from the releases. Are you doing the ajax on drop? So is this within an eventListener?

I think it would really help if you could provide the entire code / an example so I can more quickly diagnose it.

**Comment by ruudmens** [comment]
First used the master, but switch to version 7.0.0 and still the same issue. I am not using the ajax on drop, just a submit button the serialize the sortable and does a ajax post.

https://jsfiddle.net/2b3ukwed/2/

**Comment by lukasoppermann** [comment]
Hey, so I think the issue is, that you are trying to send `nodes` via ajax. If you just pick e.g. the `className` https://jsfiddle.net/2b3ukwed/63/ it is fine. So you would need to run a function over the serialized array to remove all nodes just pick the data you need from the and put them into an object.

**Comment by ruudmens** [comment]
That wont work. I got multiple lists with child items that I need.
But it's strange that the drop event from sortable get's triggered by a ajax post..

**Comment by lukasoppermann** [comment]
I don't think you can send nodes via ajax, what do you mean by you need the children? Isn't it the content you need?

If so you could just write a function that iterates over the children and collects the data. You are storing data, correct?

**Comment by lukasoppermann** [comment]
Hey @ruudmens could you get this one working? I think this issue can be closed, correct?

**Comment by ruudmens** [comment]
Yeah you can close it. It works by iterating over them

**Comment by lukasoppermann** [comment]
Nice, there are plans for improved serialization.
