### ISSUE TITLE
Can IE Fix be removed?

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#384]
Can we remove this IE fix?
 https://github.com/lukasoppermann/html5sortable/blob/master/src/html5sortable.ts#L170-L186

If not, why is it important? Can we explain in code comments why this is needed and for up to which IE versions?

**Comment by CWSites** [comment]
What was the issue that caused you to add it in the first place?

**Comment by lukasoppermann** [comment]
Hey @CWSites, there were some issues with the ghost / dragImage in IE, I don't recall exactly what though. I guess it is not needed in modern IE and Edge browsers anymore.

**Comment by kaffarell** [comment]
Issue closed because it is not present anymore in recent browsers
