### ISSUE TITLE
Hover on another element after dragstart

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#388]
When hover is active and `dragstart` fires, if an element moves into the position of the hovered item it gets the hover status.

Maybe on dragstart hover should be removed.

**Comment by mfeherpataky** [comment]
I can look into this one, as it is on my TO-DO list (it is somewhat confusing for some users that notice it), but only after #394.

**Comment by lukasoppermann** [comment]
That would be great. 👍
