### ISSUE TITLE
Enable selectstart on [contenteditable]

### ISSUE THREAD

**Issue by jzelez** [lukasoppermann/html5sortable#39]
I have ol/ul lists that have `li` elements with `[contenteditable]` attribute set on them so the user can modify them.
By default, html5sortable disables `selectstart` behaviour and thus disables normal editing on the element. 

Is this the intended behaviour?

btw. I've added `[contenteditable]` to the `not()` filter just before the `selectstart.h5s` event handler to counteract this.

**Comment by paulgibbs** [comment]
I had a similar-but-different problem with contentEditable elements inside a div. The div also contained a `<button>` which was the div's drag handle for this plugin. The `items.attr('draggable', 'true')` line (items === the wrapper for the div(s)) was breaking the contentEditable elements on iOS 7 (and in the iOS Simulator) -- but it was working fine in desktop Chrome.

I've made a local mod and set the draggable property in mouseup/down handlers, which works to fix the problem for me, though obviously isn't good enough to submit back to the plugin:

``` diff
diff --git a/sortable.js b/sortable.js
index 77ed290..4944218 100755
--- a/sortable.js
+++ b/sortable.js
@@ -52,9 +52,11 @@

       items.find(options.handle).mousedown(function () {
         isHandle = true;
+        items.attr('draggable', 'true');
       }).mouseup(function () {
-          isHandle = false;
-        });
+        isHandle = false;
+        items.attr('draggable', 'false');
+      });
       $(this).data('items', options.items);
       placeholders = placeholders.add(placeholder);
       if (options.connectWith) {
@@ -64,7 +66,7 @@
       items.attr('role', 'option');
       items.attr('aria-grabbed', 'false');

-      items.attr('draggable', 'true').on('dragstart.h5s',function (e) {
+      items.on('dragstart.h5s',function (e) {
         e.stopImmediatePropagation();
         if (options.handle && !isHandle) {
           return false;
```

**Comment by lukasoppermann** [comment]
Closing this for now, however if anyone would like to send a PR I would appreciate it.
