### ISSUE TITLE
Does not fire sortupdate when dragging an item up in list

### ISSUE THREAD

**Issue by av-nexter** [lukasoppermann/html5sortable#411]
Link to code example, with an error https://jsfiddle.net/Le3pf8zf/7/ 
Try to move "Item 2" element before "Item 1" and you will see that there is nothing in console.
If you drag item up, sortupdate event does not work, and as soon as you drag it down, it will work.

Chrome version 65.0.3325.181

**Comment by lukasoppermann** [comment]
Hey, thanks for bringing it up.

This was actually fixed recently, however it is not released yet and the dist versions in master were not updated. I just updated the master versions, but it is not released yet. I am planning to do a release really soon. Sorry for the wait, just need to make sure the release is stable.

I tried using https://lukasoppermann.github.io/html5sortable/html5sortable.js in your fiddle (rawgit somehow seemed to have a caching error) and it works fine.

As a temporary fix you can now use the master branch from github.

**Comment by av-nexter** [comment]
@lukasoppermann Thank you very much)
