### ISSUE TITLE
unnecessary delete? issue with minify: Parse error. Invalid delete operand. Only properties can be deleted

### ISSUE THREAD

**Issue by arman-ilyas** [lukasoppermann/html5sortable#414]
Hi, can you please explain the logic behind this line?
line 222:
`delete store(element).deleteData("event" + eventName);`

when I try to minify the code, it returns 
`ERROR - Parse error. Invalid delete operand. Only properties can be deleted.`

**Comment by lukasoppermann** [comment]
Thanks for spotting this one, should be fixed now.
