### ISSUE TITLE
Can't find jQuery wrapper

### ISSUE THREAD

**Issue by ninze** [lukasoppermann/html5sortable#417]
I used a jQuery plugin from https://github.com/voidberg/html5sortable, which now redirects here.

Is there jQuery wrapper available?

thanks.

**Comment by lukasoppermann** [comment]
Hey @systemist,

there is no jQuery wrapper. However you can easily use it without jquery. You just call the `sortable` function and provide a selector for the elements you want to be sortables.

```js
sortable('.sortable', {
  // … options
})
```
