### ISSUE TITLE
function sortable->sortupdate disables placeholder 

### ISSUE THREAD

**Issue by AndyPandy123123** [lukasoppermann/html5sortable#419]
sortable('.sortable')[0].addEventListener('sortupdate', function(e) disables place holder

**Comment by lukasoppermann** [comment]
Hey @AndyPandy123123 can you please provide a code example with the issue on jsfiddle? Thanks.

**Comment by AndyPandy123123** [comment]
```js
sortable('.js-sortable-target', {
  forcePlaceholderSize: true,
  acceptFrom: '.js-sortable-source,.js-sortable-target'
});

sortable('.js-sortable-source', {
  forcePlaceholderSize: false,
  acceptFrom: '.js-sortable-source'
});

sortable('.sortable')[0].addEventListener('sortupdate', function(e) {
  if((e.detail.origin.container.id != e.detail.destination.container.id) && (e.detail.destination.index>=0))
  {
    // Some code
  }
});
```

**Comment by AndyPandy123123** [comment]
if i delete the function then it works

**Comment by lukasoppermann** [comment]
With `sortable('.sortable')` you reinitialize the sortables and reset all config values. This might be the issue. I am guessing target also has the class sortable or how is this connected?

**Comment by lukasoppermann** [comment]
Closing as I guess the issue is solved, please comment if there are still issues.
