### ISSUE TITLE
Redirect to arbitrary-content.com

### ISSUE THREAD

**Issue by pmpBear** [lukasoppermann/html5sortable#420]
On Firefox 59.0.2 for Windows, 
after I sort a few elements i get redirected to a website "arbitray-content.com". 
I am using version 0.9.1 of the plugin.

My configuration is the following: 
```
sortable('.table-sortable tbody.sort', {
			handle : '.field-sortable',
			acceptFrom : 'table.table-sortable  tbody.sort',
			forcePlaceholderSize : true,
			placeholder : '<tr class="disabled"><td colspan="8"></td></tr>'
		})
```

I see in the plugin where you make this call:
 event.dataTransfer.setData('text', 'arbitrary-content');

I don't undestand why it is redirecting me to http://arbitrary-content/, that it translates automatically to arbitrary-content.com

Thank you

**Comment by lukasoppermann** [comment]
Wow, that is a very interesting issue. As you probably read, firefox used to require this to be set to work.

I am not sure if this is still the case. The correct type would actually be `text/plain`. Could you maybe change the code to `event.dataTransfer.setData('text/plain', 'arbitrary');` and see if the issue persists?

You can drag and drop links and I guess firefox interprets this as a link drop and somehow executes it. If this fixes it a PR would be nice. 👍 

Thanks.

**Comment by johnhearfield** [comment]
This is still the case.
It now redirects to arbitrary.com

**Comment by lukasoppermann** [comment]
Hey @johnhearfield do you know how to fix this?

**Comment by johnhearfield** [comment]
Try and change ``event.dataTransfer.setData('text/plain', 'arbitrary');`` to ``event.dataTransfer.setData('text/html', 'arbitrary');``

It's a recurring issue in Firefox it seems. I tried ``event.preventDefault()`` but that just broke the thing

**Comment by lukasoppermann** [comment]
Hey @johnhearfield thanks. Do you want to send a PR for this?

Do you know for sure that this does not have any repercussions? E.g. has this solution be discussed somewhere already?

**Comment by johnhearfield** [comment]
Theres a few comments here that explain it:
https://stackoverflow.com/questions/19055264/why-doesnt-html5-drag-and-drop-work-in-firefox

I haven't tried setting it as just **text** instead of **text/html**

According to this thread, it seems you should use text:
https://stackoverflow.com/questions/12803235/drag-and-drop-not-working-in-ie-javascript-html5

I'll change it locally to 'text' to see if that works in Firefox, Chrome and Safari (macOS)
