### ISSUE TITLE
Multiple problems with table <td> sorting

### ISSUE THREAD

**Issue by thomasburbeck** [lukasoppermann/html5sortable#426]
### Supporting Information:
- I'm using the latest version of html5sortable
- I am primarily testing in Firefox (latest version) on MacOS. Testing in Safari I don't seem to have a problem right now.

### The Problem(s)
I'm having a couple of different problems trying to use this library to sort td elements inside a tr. 

The first problem is that when dragging and dropping an element it causes the browser to redirect to http://www.arbitrary.com; I narrowed this down to being the following:

`        event.dataTransfer.setData('text/plain', 'arbitrary');
`

Converting this to `'text/html` solved the problem for me - but I'm not sure if there is a better way of solving this, if it affects anything else or it needs pull requesting in as a fix. Any thoughts on this?

Problem number 2 is where I'm currently stuck; occasionally my drag and dropping works inside the table row but usually it doesn't. I'm using an element with a class .EditorBlockSelector for my handle because I use this element with an absolute position and a higher z-index to display over the elements on hover. However; removing the handle and hover effects and just returning to a simple td sort inside a tr gives me the same result - again just to repeat this appears mainly in Firefox.

I am using these options to setup html5sortable:

```js
     placeholder: '<div style="background-color: #ccc;">&emsp;</div>',
      forcePlaceholderSize: true,
      handle: '.EditorBlockSelector'
```

This is my HTML structure (badly formatted because I don't know how to format it correctly):

```html
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="Content">
          <tr class="Sortable">
              <td align="center" valign="top" width="50%" class="templateColumnContainer">
                <div class="EditorBlock">
                  <div class="EditorBlockSelector"></div>
                  <table border="0" cellpadding="10" cellspacing="0" width="100%" class="Content">
                      <tr>
                          <td class="leftColumnContent">
                              <img src="http://placekitten.com/g/480/300" width="280" style="max-width:280px;" class="columnImage" />
                          </td>
                      </tr>
                      <tr>
                          <td valign="top" class="leftColumnContent">
                              <h1>Left Column</h1>
                              Lorem ipsum dolor sit amet.
                          </td>
                      </tr>
                  </table>
                </div>
              </td>
              <td align="center" valign="top" width="50%" class="templateColumnContainer">
                <div class="EditorBlock">
                  <div class="EditorBlockSelector"></div>
                    <table border="0" cellpadding="10" cellspacing="0" width="100%">
                      <tr>
                          <td class="rightColumnContent">
                              <img src="http://placekitten.com/g/480/300" width="280" style="max-width:280px;" class="columnImage" />
                          </td>
                      </tr>
                      <tr>
                          <td valign="top" class="rightColumnContent">
                              <h1>Right Column</h1>
                              Lorem ipsum dolor sit amet.
                          </td>
                      </tr>
                  </table>
                </div>
              </td>
          </tr>
      </table>
```

**Comment by lukasoppermann** [comment]
Hey, I am not sure, but I think you need to use `tr` as an item. Dragging `td` does not work. If you find a fix for it you are more than welcome to send a PR.
