### ISSUE TITLE
elementHeight does not take in to account the box-sizing method

### ISSUE THREAD

**Issue by tomsykes** [lukasoppermann/html5sortable#432]
the code used to fix the height of the placeholder does not take in to account the box-sizing method - and always adds top/bottom padding to computed height. When an element has box-sizing: border-box, the padding is already included in the computed height.

I use sortable version: 0.9.2

### How can the issue be reproduce the problem?
 - ensure the sortable items have top/bottom padding and box-sizing: border-box
 - enable the forcePlaceholderSize option
 - sort the items

**Comment by tomsykes** [comment]
It seems my initial tests were wrong... as far as I can tell, the computed style for height always includes padding, and border. elementHeight should not be adding padding to the height.

**Comment by lukasoppermann** [comment]
This depends on the use case. Adding padding does make sense. However I agree that it is not always desired.

Could you maybe send a PR which allows the user to toggle this behavior with an option?

**Comment by tomsykes** [comment]
From my browser based tests (chrome, ff, ie11, edge), padding is always included within the computed style value of the element's height (regardless of the box-sizing value - this was a red herring)... so, there's never a case for adding padding again.

Sadly, I think the test environment doesn't produce computed styles in the same way as a real browser, so while the test passes, the real life experience is broken.

**Comment by lukasoppermann** [comment]
Ahh, sorry, I might have misunderstood you.

So in this page: https://lukasoppermann.github.io/html5sortable/index.html the first sortable has padding and `forcePlaceholderSize: true`. It seems to work there. Can you explain what the issue is again with this example? Thank you.

**Comment by tomsykes** [comment]
I'll be honest with you, I'm stumped.

In my code, when I drag an element, the placeholder is being given a height value which is equal to height + 2 * padding. I've been through the full list of computed values for both the html5sortable example you've linked, and my own, and tested the differences, and I still can't find the cause!

If I have time a little later I will try to put together an example, but for now I guess it's just my problem.

Edit: it's been bugging me (lots), so after a fair bit of fiddling and not checking results properly, I now have a jsfiddle that demonstrates it, and my original suspicion is now confirmed, it is box-sizing.
https://jsfiddle.net/tomsykes/0n0t9qgp/

**Comment by lukasoppermann** [comment]
Yep, makes sense, thanks for the example.

Would you be able to send in a PR with a fix? The height is calculated here: https://github.com/lukasoppermann/html5sortable/blob/master/src/elementHeight.ts

So I guess you could test for the box sizing mode and adapt the behavior? Or maybe you have a better solution. 

Thanks for digging into this.

**Comment by tomsykes** [comment]
Sure, np.

My only question is - what should the behaviour be...

1. do we assume that the placeholder also has border-box sizing? In which case setting the height to the computed height (which includes padding) should be fine?
2. do we force the the placeholder to also be border box if the other items are border box?
3. do we check what box-sizing the placeholder has, and set the height accordingly?

Obviously the simplest/easiest solution is (1), (2) is a slightly better solution but is obviously more complex. I'm not sure i like (3) very much.

**Comment by lukasoppermann** [comment]
I don't think we can assume that the placeholder has `border-box sizing`, so we would need to force it. 

Does this make sense to you?

**Comment by lukasoppermann** [comment]
Hey @tomsykes do you have any process here? Is there something I can merge? Thanks.

**Comment by tomsykes** [comment]
Honestly, I'm pretty busy - it seemed like you went for my suggested option 2, but didn't say that explicitly... and option 2 added quite a bit of complexity, that I wasn't sure how to deal with... since at the moment there's a method that is getting the height, and not any other css properties.

**Comment by lukasoppermann** [comment]
Hey, @tomsykes so you are not working on it, due to time constraints, correct?

**Comment by tomsykes** [comment]
More to do with the lack of guidance on how to fix it... if it were my own project, I would likely refactor this part of it to suit my most common scenarios. As it's not mine, I'm somewhat reliant upon you for guidance.

As it is - I've managed to work around the problem on the site I was using it for with CSS. I guess if I hadn't worked around it, I would have more time to spend helping to fix it for others - but I also feel that by raising the issue, others might also be able to work around the problem with CSS.

**Comment by lukasoppermann** [comment]
Hey, I was under the impression that I did guide you on this. I am sorry if you feel different.

If you want to continue on this, please let me know how I can better help you.

If you do not have enough time maybe you could post a description of the issue & workaround so that other people can learn from what you figured out?

Thanks.

**Comment by tomsykes** [comment]
The problem is that different box-sizing values cause an element's height to be calculated differently. border-box includes padding within the height calculation, where as content-box does not.

When inserting a placeholder, html5sortable calculates the height as css-height + top and bottom padding (even though the css-height might already include padding).

See https://jsfiddle.net/tomsykes/0n0t9qgp/

A potential quick fix is to set box-sizing to content-box on the sortable items, but this isn't always possible/desirable (other thing are made easier by having border-box, which is why some frameworks like bootstrap set it by default for all elements).

The simplest long term solution is to take in to account the value of the box-sizing property of the sortable item, and either include or exclude padding accordingly, but my feeling was that you rejected this solution.

The other options I proposed were more complicated due to the way things are laid out... elementHeight.ts is only deals with height, where as we would now need to deal with other properties too.

I'm not au fait with typescript, and don't have any clue about the tool chains you've used to build the project - so there is too great a barrier to me implementing the latter fix at the present time. Hopefully I've given you sufficient information to do whichever fix you feel is appropriate.
