### ISSUE TITLE
Load serialized list from database

### ISSUE THREAD

**Issue by mjpramos** [lukasoppermann/html5sortable#436]
Hi! Nice plugin.
I really like the serialize method so we can store the sorted elements.
But how can we use that data (pulled from a database for example) to load at a later time the saved order?
Can anyone provide an example?
Thanks

**Comment by lukasoppermann** [comment]
Hey, sorry for the late reply. This is not possible without doing it yourself. There is no method to build a list from data or anything.

You will have to writ this yourself.

**Comment by mjpramos** [comment]
Hi! Thanks. Got it sorted out.
