### ISSUE TITLE
Create HTML from serialized JSON

### ISSUE THREAD

**Issue by alucidwolf** [lukasoppermann/html5sortable#444]
### I'm opening this issue because:
I am wondering if I am approaching this the correct way, or if you have encountered this before and have a solid solution.

### supporting information:
- I use sortable version: 0.9.3
- I tested in the following browser (incl. versions): Chrome 67.0.3396.87, IE 11
- Windows, OS X/macOS, or Linux?: Windows

### How can the issue be reproduce the problem?
Please add a complete description of how to reproduce the problem.
I have a list, simple UL > LI's
I serialize it using the method `sortable('.sortable', 'serialize');`
I stringify it `JSON.stringify(contentSerialized)` and it looks like the below
```
[
  {
    "container": {
      "node": {
        "h5s": {
          "data": {
            "opts": {
              "items": null,
              "connectWith": null,
              "disableIEFix": null,
              "acceptFrom": ".toolbar, .builder",
              "copy": false,
              "placeholder": "<div class=\"sort-placeholder\">&nbsp;</div>",
              "placeholderClass": "sortable-placeholder",
              "draggingClass": "sortable-dragging",
              "hoverClass": false,
              "debounce": 0,
              "throttleTime": 100,
              "maxItems": 10,
              "customDragImage": null,
              "handle": ".icon-menu2"
            },
            "_disabled": "false",
            "items": null,
            "acceptFrom": ".toolbar, .builder"
          }
        },
        "isSortable": true
      },
      "itemCount": 7
    },
    "items": [
      {
        "parent": {
          "h5s": {
            "data": {
              "opts": {
                "items": null,
                "connectWith": null,
                "disableIEFix": null,
                "acceptFrom": ".toolbar, .builder",
                "copy": false,
                "placeholder": "<div class=\"sort-placeholder\">&nbsp;</div>",
                "placeholderClass": "sortable-placeholder",
                "draggingClass": "sortable-dragging",
                "hoverClass": false,
                "debounce": 0,
                "throttleTime": 100,
                "maxItems": 10,
                "customDragImage": null,
                "handle": ".icon-menu2"
              },
              "_disabled": "false",
              "items": null,
              "acceptFrom": ".toolbar, .builder"
            }
          },
          "isSortable": true
        },
        "node": {},
        "html": "<li role=\"option\" aria-grabbed=\"false\">\n <div>\n <span class=\"icon-menu2\" draggable=\"true\"></span>builder item 1\n </div>\n </li>",
        "index": 0
      },
...

    ]
  }
]
```

Should I just loop through the "items" array and extract the VALUE for the HTML keys, create a string, remove the extra '\' and '\n' characters, and then append that to another div?

### Thank you for contributing!
- Please make sure your contribution is in line with the contribution guidelines: 
  https://github.com/lukasoppermann/html5sortable/blob/master/CONTRIBUTING.md

- Participation in this open source project is subject to the Code of Conduct:
  https://github.com/lukasoppermann/html5sortable/blob/master/CODE_OF_CONDUCT.md

Before creating a feature requests, please review the existing feature requests and make sure there isn't one that already describes the feature you are missing:
https://github.com/lukasoppermann/html5sortable/issues?q=is%3Aopen+is%3Aissue+label%3Afeature

#### What's the feature?
The new feature would be something along the lines of deserialize to HTML?

#### What problem is the feature intended to solve?
It would allow the exporting of sorted list to a DB so that it can be retrieved later and used to rebuild the same list in the correct order with the proper content.

#### Is this feature similar to an existing feature in another project?
Not that I have seen in my review of this repo

**Comment by lukasoppermann** [comment]
Hey,

so if you want to create a PR for this I think the best option is to create a deserialise function that takes a callback function.

This call back would take a list of items. By default it could have a function that just looks for an html property in the items array items and puts this in a `<li>` but the user could overwrite this callback to basically do anything to adjust for different data. However you need to make sure to handle nested data for nested lists correctly.

**Comment by alucidwolf** [comment]
You got it @lukasoppermann - I will fork this repo and work on it. Then submit a PR when done or if I need some help or feedback.

**Comment by lukasoppermann** [comment]
Awesome, looking forward to your PR. Please make sure to keep it as flexible as you can, to allow for different use cases.

**Comment by lukasoppermann** [comment]
Closed due to inactivity.
