### ISSUE TITLE
Cannot Drop into the first item occasionally

### ISSUE THREAD

**Issue by huskier** [lukasoppermann/html5sortable#45]
Hi,

There is already an issue item in the list, but I think my situation is a little different from that one. When I drag a new item into the list, sometimes I can drag an item into the first place, sometimes I cannot. It's very wired. My example as following (modified from the GitHub source example). I tested the code on ChromeV37 and FirefoxV33.  

The example can be found in the following link:
https://gist.github.com/anonymous/960c0b7b447ab89ae465

Thanks in advance!

**Comment by lukasoppermann** [comment]
@huskier does this issue persist with the current version? If so could you please create a live example on jsfiddle or codepen?

**Comment by lukasoppermann** [comment]
If this is still valid, please send a live demo with the latest version / a PR with a failing test or/and a bugfix.
