### ISSUE TITLE
FireFox occasionally redirects to "arbitrary.com"

### ISSUE THREAD

**Issue by pfriedl** [lukasoppermann/html5sortable#450]
### I'm opening this issue because:
After dragging and dropping table rows, FireFox triggers a search for "arbitrary", which automatically redirects to arbitrary.com

### supporting information:
- I use sortable version: 0.9.3
- I tested in the following browser (incl. versions): FireFox 61.0.1 64 bit 
- Windows, OS X/macOS, or Linux?:### How can the issue be reproduce the problem? Windows 10, MacOS
Please add a complete description of how to reproduce the problem.

I've got a table of data and making the rows sortable. In FireFox, after about 10 drag and drops, FireFox immediately triggers a search for "arbitrary" and automatically redirects to arbitrary.com

I believe this issue is related to line 458 of html5sortable.js:
event.dataTransfer.setData('text/plain', 'arbitrary');

**Comment by lukasoppermann** [comment]
Related to #420 I actually have no idea how to fix it. If you have any insight, please send a PR.

**Comment by ericparshall** [comment]
In case anyone is interested, I have been able to stop this from happening by changing:

```
event.dataTransfer.setData('text/plain', 'arbitrary');
```

to this:

```
event.dataTransfer.setData('text/plain', event.target.id);
```

I will try to get a PR for this but I haven't used TypeScript before, so it may take a while.

**Comment by lukasoppermann** [comment]
Hey @ericparshall, thank you, looking forward to the PR. I think TypeScript should not provide an issue for this change at all. At this point its only vanilla JS. If you need any help, please let me know.

**Comment by ericparshall** [comment]
Thanks for reminding me @lukasoppermann. The tricky part for me was getting the mock DragEvent to have target object so the tests would pass. Please let me know if there is anything I need to change.
