### ISSUE TITLE
What specific polyfills are needed?

### ISSUE THREAD

**Issue by brendon** [lukasoppermann/html5sortable#457]
### I'm opening this issue because:
I was wondering (in order to be efficient) what particular polyfills are needed for IE11 etc... support? I suppose it's easier just to use the Financial Times link, but if you know for sure which polyfills are required that'd probably be helpful to know :)

**Comment by lukasoppermann** [comment]
Hey, I can't tell you this anymore. For IE11 there are probably quite a bit, because many methods and things are not supported, e.g. `Map`.

**Comment by brendon** [comment]
That's all good. I assume it'd get worse as time went on too.
