### ISSUE TITLE
Unable to move item to last position in IE11

### ISSUE THREAD

**Issue by petrinecp** [lukasoppermann/html5sortable#460]
### I'm opening this issue because:
Hi, when using html5sortable in IE11, I'm unable to move an item to the last position of the list. I've created a JSBin to demonstrate the issue.
http://jsbin.com/ridunafeya/edit?html,css,js,output

### supporting information:
- I use sortable version: 0.9.4
- I tested in the following browser (incl. versions): IE11
- Windows, OS X/macOS, or Linux?: Windows

### How can the issue be reproduce the problem?
Try dragging an item in the list to the bottom of the list.

**Comment by petrinecp** [comment]
OK, so I've debugged this and it's a simple fix, the problem is in the offset function where window.scrollX and window.scrollY return undefined in IE11.
See the [notes](https://developer.mozilla.org/it/docs/Web/API/Window/scrollX#Notes) for the scrollX property where window.pageXOffset and window.pageYOffset aliases are suggested to be used for better cross-browser compatibility.

**Comment by lukasoppermann** [comment]
Nice, could you send a PR with the fix? That would be great. Thanks

**Comment by petrinecp** [comment]
Hi, of course. Here it is #464.

**Comment by lukasoppermann** [comment]
Thanks.
