### ISSUE TITLE
fsevents in `dependencies` breaks all install on platforms !== OSX

### ISSUE THREAD

**Issue by gierschv** [lukasoppermann/html5sortable#466]
### I'm opening this issue because:

v0.9.5 breaks all the `npm/yarn install` on Linux because of the `fsevents` modules in `dependencies`. Since this dependency is no longer optional, the installation will always fail.

Thank you!

**Comment by lukasoppermann** [comment]
Okay, this should be fixed, correct? Can you please confirm? Thanks.

**Comment by gierschv** [comment]
@lukasoppermann Perfect! Thanks for the quick update.
