### ISSUE TITLE
new Map(iterable) break in IE11

### ISSUE THREAD

**Issue by kp-phongpt** [lukasoppermann/html5sortable#474]
new Map(iterable) not yet support in IE11 so this code will be break: 
![image](https://user-images.githubusercontent.com/41980348/48830193-99790780-eda6-11e8-87eb-5bc861dab81b.png).

I suggest replace this code when in IE11: this._config = new Map(Object.entries(mergedConfig));
with this:
Object.entries(mergedConfig).forEach(function (option) {
    this._config.set(option[0], option[1]);
}.bind(this));

**Comment by lukasoppermann** [comment]
Hey @kp-phongpt,

thank you for the mention, but this lib only supports IE11 with polyfills. So you will need to use the Map polyfill.

This is to keep the code modern and simple (considering IE11 is a 5 year old browser). I know, depending on the country and/or industry IE11 might be more popular, but nevertheless we are focusing on simple code.

**Comment by kp-phongpt** [comment]
@lukasoppermann can you send me the Map polyfill link? I can't found it on google. Thank you!
