### ISSUE TITLE
Is it possible to drag item to the container not on the list ?

### ISSUE THREAD

**Issue by bat-uchral** [lukasoppermann/html5sortable#480]
### supporting information:
- I use sortable version:
- I tested in the following browser (incl. versions):
- Windows, OS X/macOS, or Linux?:

### How can the issue be reproduce the problem?
Please add a complete description of how to reproduce the problem.

### Thank you for contributing!
- Please make sure your contribution is in line with the contribution guidelines: 
  https://github.com/lukasoppermann/html5sortable/blob/master/CONTRIBUTING.md

- Participation in this open source project is subject to the Code of Conduct:
  https://github.com/lukasoppermann/html5sortable/blob/master/CODE_OF_CONDUCT.md

Before creating a feature requests, please review the existing feature requests and make sure there isn't one that already describes the feature you are missing:
https://github.com/lukasoppermann/html5sortable/issues?q=is%3Aopen+is%3Aissue+label%3Afeature

**Comment by lukasoppermann** [comment]
You can have multiple sortables but if you want to drag it on something else you need to code your own events.

**Comment by bat-uchral** [comment]
Is it possible to behave connectWith list same as empty list ? When one of the list is empty items can be drag in to empty list within the empty list's height. Instead of that two list can be drag and drop each others height.

**Comment by lukasoppermann** [comment]
Sorry, I don't understand what you mean. When you have an empty list you need to set a min-height or give it some padding to make sure there is something to drag on. But I am not sure that is what you are asking about.
