### ISSUE TITLE
jQuery-Tubular Plugin, html5Sortable drag and drop chrome bug. 

### ISSUE THREAD

**Issue by developerPaul84** [lukasoppermann/html5sortable#481]
Built a drag and drop webpage builder where users can drag and drop elements onto a template, they can also add a youtube video as a video background. 

Bug

If a user loads a background video before dragging and dropping anything in to the page, this stops the users from being able to add from the drag and drop elements from html5Sortable.  The page does not crash. This has only happened in the latest version of Chrome. All other browsers if works as expected. 

https://codepen.io/TerabitPaul/pen/jXzMOO

**Comment by lukasoppermann** [comment]
Hey, I have the feeling it worked for me. If this is only in the latest chrome, it might not be a bug with this package. However if you find out what causes it, feel free to mention it and send a PR. Thanks.

**Comment by lukasoppermann** [comment]
Closed due to inactivity.
