### ISSUE TITLE
support shadowRoot handlers 

### ISSUE THREAD

**Issue by christophe-g** [lukasoppermann/html5sortable#487]
It would be great to be able to also query shadowRoot when specifying handlers. This would be useful for instance when we are using `html5sortable` with Polymer (2 or 3): 

```html
<dom-module id="custom-drag-wrapper">
  <template>
      <iron-icon id="drag" icon="editor:drag-handle" alt="drag me"></iron-icon>
     <slot></slot>
  </template>
</dom-module>
```

and then : 
```js
 // initiate sortable with handler in shadowRoot:
 sortable( ..., {handle: '#drag'});
```

Submitting a PR soon.

**Comment by lukasoppermann** [comment]
I am looking forward to the PR, this sounds very interesting.
