### ISSUE TITLE
How can we use this plugin for sorting multiple columns and rows in a matrix.

### ISSUE THREAD

**Issue by wpgeek922** [lukasoppermann/html5sortable#49]
Hi!, Does this plugin support multiple element sorting?. I means dragging or sorting child elements when their parent element is also set to draggable='true'.

**Comment by jacobsvante** [comment]
~~I think we might be looking for the same thing. If there's a sortable parent nested inside another sortable parent it's always the "outmost" one that gets grabbed. Same thing right?
Maybe it's something with bubbling of the drag events.~~
My problems have been fixed in #68.

**Comment by lukasoppermann** [comment]
This should be fixed by #68. I am doing the same and after my fix it works fine for me.

**Comment by wpgeek922** [comment]
Great! I'll try it.

**Comment by lukasoppermann** [comment]
Fixed by #68
