### ISSUE TITLE
No `dist` folder in v0.9.10

### ISSUE THREAD

**Issue by kyle-west** [lukasoppermann/html5sortable#495]
### I'm opening this issue because:

My project uses the `html5sortable/dist/html5sortable.min.js` file, and it looks like the whole `dist` folder is missing. Your build step must not have gotten get published to master. Back pinning to v0.9.8 solved the problem for me for now, but I thought I would make you aware of the problem.

### supporting information:
- I use sortable version: 0.9.10
- I tested in the following browser (incl. versions): N/A
- Windows, OS X/macOS, or Linux?: N/A

**Comment by lukasoppermann** [comment]
Hey @kyle-west, how do you install the package? It is by design, as the dist folder is now listed in `.gitignore` but installing via npm should give you the dist folder.

Can you give me a reasonable use-case for installing it differently? I was not aware this is a thing, so I may make the change a breaking change (semver).

Sorry for the inconvenience in any case.

**Comment by kyle-west** [comment]
We install the package via `bower` along with our other components. We use `webpack` to handle our build step, along with some other build processes custom to our stack. All our other components use a `dist` or `build` section of the repo that we reference. 

Might I ask why you stopped tracking the `dist` folder? Does everyone who consumes this now have to build your repo first to use it?

**Comment by lukasoppermann** [comment]
Hey, 

no if you install the package via npm you get the `dist` folder. The issue with including the `dist` folder in git, is that people often add them when sending pull requests which makes for an annoying flow of asking them to clean up the pr by removing the files from dist.

I am not aware of a way to let only me push the `dist` folder to master and keeping it ignored for all others. I guess you don't know of a way either?

I do see your issue though, darn. You can't use npm tarballs in bower, correct?

**Comment by kyle-west** [comment]
Yeah bower just pulls down the repo from github, so tarballs are not an option for us.

And as far as making the `dist` folder not pushable to anyone except to you, there is a possibility. Consider the following:
- still keep the dist folder ignored on the master branch
- when a PR is merged, create a branch called `latest-build` (or whatever), unignore the dist folder on that branch, run the build step on that branch, commit to the branch and push to github. 
- instead of making releases from the `master` branch, you can make releases from the `latest-build` branch just using the gui or the cli.

Travis CI I know can be configured to run tests and publish builds via a script. That script can be configured to run when there are merges to the master branch if we wanted to automate it. Or a script at least could easily be made to do the same thing manually from your machine.

**Comment by kyle-west** [comment]
```sh
git tag $VERSION_NUMBER latest-build; 
git push;
```
will handle publishing releases from the `latest-build` branch

**Comment by lukasoppermann** [comment]
I'll look into it.

**Comment by kyle-west** [comment]
Thank you. I appreciate your willingness to work with me on this.

**Comment by lukasoppermann** [comment]
Hey @kyle-west I released a new version like this. All that is left now is to somehow automate this in the `npm version` flow, so that it can not be forgotten. Do you have experience with this?

**Comment by kyle-west** [comment]
Thank you so much! 

Yes I do. Since you are using Travis, this is as easy as adding a script to be ran after a successful CI build/test. 

Add the following to the `.travis.yml` config
```yml
after_success:
  - sh ./path/to/your/release/script # or whatever command you want
```
Make sure in the script that the `TRAVIS_BRANCH` environment variable is set to `'master'` and that `TRAVIS_PULL_REQUEST` is `'false'` (both vars will be a string), before creating any releases, that way a release is not created during every pull request.

**Comment by lukasoppermann** [comment]
Well currently I just run npm build & npm version patch by hand.

**Comment by kyle-west** [comment]
Sorry for the delay, but I think #497 is a solution that fits both our needs.

**Comment by lukasoppermann** [comment]
Awesome, I think I will need some tweaks, so that it automatically works with the `npm version {major|minor|patch}` command, but this is an awesome start, thank you very much. I will merge the PR when I have time to adjust it afterwards.
