### ISSUE TITLE
Dragover event doesn't fire in iFrame with security flags on

### ISSUE THREAD

**Issue by roschler** [lukasoppermann/html5sortable#496]
In an iFrame with web security flags turned on, the `dragover` event never fires thereby breaking the drag and drop feature of html5sortable.  Apparently the web security settings do this to prevent dragging and dropping content outside the bounds of the iFrame.  Unfortunately I don't have control over the iFrame since that iFrame and the security settings applied to it are controlled by Twitch and my code, a Twitch extension, runs in that iFrame they provide and launch with my page content as the URL source for the iFrame.

Is there a way to fix this, perhaps a workaround involving using some other technique or event that would not conflict with the iFrame's web security settings?

**Comment by lukasoppermann** [comment]
Hey, sorry I have not really any idea of how to fix it. If you figure it out please send a PR, thanks. 👍

**Comment by KenorFR** [comment]
Juste replace
`!(event instanceof Event)`
by
`event.constructor.name !== 'DragEvent'`

in setDragImage.ts to work in iframe.

I don't know why, but chrome can't detect that "event" is an instance of "Event" when the selector is in an iframe. And so, it blocks the rest.

**Comment by lukasoppermann** [comment]
Hey @KenorFR, did you test if it is working in all other major browser? If it is, could you send a PR to fix this?

**Comment by lukasoppermann** [comment]
Closed due to inactivity and uncertainty that the proposed fix makes sense in a bigger context. In Firefox `event.constructor.name` equals "Function" so this would always return false.
