### ISSUE TITLE
How to change element between columns programmatically

### ISSUE THREAD

**Issue by fabiomlferreira** [lukasoppermann/html5sortable#499]
I have a problem I have 2 columns and the user should move some elements from de left column to the right column but the left column it's huge and if the user scrolls down the right column disappear from the screen.

I want to put a button in each element from the left column and if the user click on it this element goes automatically to the end of the right column. 
This is possible? How can I do it?

**Comment by lukasoppermann** [comment]
Hey, there is no dedicated command for this in the module, but you can easily do this with default dom commands.

Just do something like this:
```js
let sortableRight = document.querySelector('.yourSortableRight')
// item should be extracted from the click event in the button that is supposed to move it.
sortableRight.appendChild(item)
```
