### ISSUE TITLE
Strange issue with bower.

### ISSUE THREAD

**Issue by jimjeffers** [lukasoppermann/html5sortable#50]
Hey there,

I found that this package was breaking wiredep in my build process. When this package is installed and included in my bower file. I get an error from wiredep:

Running "wiredep:target" (wiredep) task
Warning: Cannot read property 'main' of undefined Use --force to continue.

I also noticed that when I run:

```
→ bower install
bower html.sortable#~0.1.6      cached git://github.com/voidberg/html5sortable.git#0.1.6
bower html.sortable#~0.1.6    validate 0.1.6 against git://github.com/voidberg/html5sortable.git#~0.1.6
bower html.sortable#~0.1.6     install html.sortable#0.1.6

html.sortable#0.1.6 app/bower_components/html.sortable
```

And then:

```
→ bower prune
bower uninstall     html.sortable
```

It seems bower does not know the package is there and prunes it. I couldn't spot any obvious problem with the bower.json file. Any ideas?

**Comment by voidberg** [comment]
I can't replicate this issue (been using 0.1.6 fine with wiredep). Could you create a minimal project that exhibits this issue so I can see what's going on?

**Comment by lukasoppermann** [comment]
@jimjeffers is this still an issue?
