### ISSUE TITLE
 'dragstart' and 'dragend' event listeners not removed from sortable element on destroy

### ISSUE THREAD

**Issue by lachdoug** [lukasoppermann/html5sortable#514]
`_destroySortable` needs 
<pre>removeEventListener(sortableElement, 'dragstart');
removeEventListener(sortableElement, 'dragend');</pre>

[See issue #512 for background](https://github.com/lukasoppermann/html5sortable/issues/512)

**Comment by lukasoppermann** [comment]
Fixed in #516
