### ISSUE TITLE
Dragging an image in Firefox loads the image URL

### ISSUE THREAD

**Issue by tbhockey** [lukasoppermann/html5sortable#518]
### I'm opening this issue because:
I am experiencing an issue when dragging images in Firefox. After dragging is complete, I am redirected to URL of the image that was dragged. Works as expected in other browsers.

### supporting information:
- I use sortable version: 0.9.16
- I tested in the following browser (incl. versions): FF 71
- Windows, OS X/macOS, or Linux?: macOS 10.14.6

### How can the issue be reproduce the problem?
I can reproduce this problem given the following:

```
<ul class="sortable images-container" aria-dropeffect="move">
  <li class="uploaded" role="option" aria-grabbed="false">
    <img src="https://www.samplesite.com/image1.jpg" draggable="true">
  </li>
  <li class="uploaded" role="option" aria-grabbed="false">
    <img src="https://www.samplesite.com/image2.jpg" draggable="true">
  </li>
  <li class="uploaded" role="option" aria-grabbed="false">
    <img src="https://www.samplesite.com/image3.jpg" draggable="true">
  </li>
  <li class="uploaded" role="option" aria-grabbed="false">
    <img src="https://www.samplesite.com/image4.jpg" draggable="true">
  </li>
  <li class="uploaded" role="option" aria-grabbed="false">
    <img src="https://www.samplesite.com/image5.jpg" draggable="true">
  </li>
</ul>
```

Forgive me if this specific issue has already been brought up, but i was unable to find it, at least in open issues. Thank you.

**Comment by lukasoppermann** [comment]
Hey @tbhockey, sadly this is a known problem with firefox. There was no way of fixing this for some time. I don't know if this has changed, but if you find a way to improve or completely fix this behavior it would be great if you could send a PR.

**Comment by tbhockey** [comment]
Understood, thank you for the response.

**Comment by Barabazs** [comment]
FYI I have no issues on FF 75.0

**Comment by lukasoppermann** [comment]
Closed due to fix in FF 75
