### ISSUE TITLE
Drag & Drop is not working on iOS

### ISSUE THREAD

**Issue by wearecroma** [lukasoppermann/html5sortable#522]
How can I make it work on an iOS device?

**Comment by lukasoppermann** [comment]
Hey, sadly iOS is a bit of an issue with html5 drag & drop. If you do find a way to make it work, please send a PR and let me know.

**Comment by paulguz** [comment]
Using this in conjunction with [DragDropTouch](https://github.com/Bernardo-Castilho/dragdroptouch) works well for us.

**Comment by andreibaca** [comment]
According to https://caniuse.com/dragndrop iOS browsers do not yet support html5 drag and drop API.

**Comment by lukasoppermann** [comment]
Thanks @andreibaca, I think we can probably close this issue as a won't fix until iOS Safari supports drag and drop.
