### ISSUE TITLE
AngularJS 1.3.x (and 1.2.x) compatibility

### ISSUE THREAD

**Issue by bdauton** [lukasoppermann/html5sortable#53]
Hi,

It seems that html5sortable isn't compatible with AngularJS 1.3.x. I've tried to change in angular-ngRepeat-connected.html AngularJS and jQuery versions and there were weird issues.

It doesn't seem to be directly related to jQuery 2.x version (required by AngularJS 1.3.x) because when I've tried with jQuery 2.1.1 and AngularJS 1.0.7 in angular-ngRepeat-connected.html, it worked.

Any idea of what's going wrong?

Thanks,

**Comment by voidberg** [comment]
Weird, I used this in an Angular 1.3 app a couple of days ago and it worked fine. Will investigate.

**Comment by bdauton** [comment]
The problem I have is when I drop an item into a connected list, this item is duplicated in the DOM. Angular model is well updated and there's no duplicate, but the DOM is completely messed up.

**Comment by lukasoppermann** [comment]
Hey @bdauton does this issue persist? Do you have a fix for it and could send a PR?

**Comment by lukasoppermann** [comment]
@bdauton did you have any time to test this?
