### ISSUE TITLE
Items draggable over "fixed" items

### ISSUE THREAD

**Issue by ap-prog** [lukasoppermann/html5sortable#531]
I have a list with many items in it. The first two items and the last item are set as not sortable.

It's possible to drag the, say, 12th item above the first of second item.

Is there some way to prevent items being dropped above the **not** sortable items? Or is there some way I can send the item back after the second item without me needing to manipulate the DOM directly?

**Comment by lukasoppermann** [comment]
Hey @ap-prog sadly no. 

The only idea would be to capture the events and check the items position. If the first item is not first anymore you could set it to the beginning of the list.

I have currently no idea of how to change the plugin to allow for this behaviour without breaking other behaviours, but if you find a way, let me know and maybe you could send a PR.

You can of course add the first item in a separate list that is not a sortable, if that works for your case.

**Comment by ap-prog** [comment]
I tried capturing events but it turned out to be to much effort. Instead I've nested a list as you suggested and that does what I need. Thanks.
