### ISSUE TITLE
Dynamic nested list example

### ISSUE THREAD

**Issue by ap-prog** [lukasoppermann/html5sortable#532]
I have a list into which other lists are added dynamically. So I can end up with a list like this:

<ol id="home">
  <li>1</li>
  <li>
    <ol class="dyn">
      <li>3</li>
      <li>4</li>
      ...
    </ol>
  </li>
  <li>5</li>
  <li>6</li>
  <li>
    <ol class="dyn">
      <li>7</li>
      <li>8</li>
      <li>9</li>
      ...
    </ol>
  </li>
  <li>10</li>
  ...
</ol>

I need to be able to drag list items into and out of nested lists, between nested lists, and to drag a nested list to a different position in '.home' (but not into another nested list. So far I've managed to drag nested lists and to drag items out of a nested list but not to drag an item from ''.home' into a nested list.

The issue seems to be that nested lists are added dynamically :-(

Could you please provide an example which demonstrates all the things I need?

**Comment by lukasoppermann** [comment]
Hey, from the top of my head I would say you need to use the **reload** command (https://github.com/lukasoppermann/html5sortable#reload) once the list is added on all other lists. 

But if you can provide a demo with the issue e.g. on codepen it would be easier to diagnose the issue.

**Comment by ap-prog** [comment]
I've created a pen
[https://codepen.io/ap_prog/pen/MWwZEpr](url)
which does mostly what I need but I can't get nested lists ('groups' I call them) to change position in the parent list.

**Comment by ap-prog** [comment]
The pen url is misbehaving. Here it is again
https://codepen.io/ap_prog/pen/MWwZEpr

**Comment by ap-prog** [comment]
I've done a new pen
https://codepen.io/ap_prog/pen/ExjrBwz
The only issue I appear to have is that I can drag a nested list into another nested list (in the same parent list) but I need to prevent nesting going more than one level ie. I shouldn't be able to drag a nested list into another nested list,

**Comment by lukasoppermann** [comment]
hey @ap-prog, great that you could make some progress. 

To clarify:

1. you need to have lists and and items both in the "home" sortable
2. you need to be able to organize/sort the lists
3. Lists are not supposed to be nested within other lists, but only sortable within the "home" list

Is that correct, or is there anything missing/wrong?

**Comment by ap-prog** [comment]
Yes but also whenever the home list, or a nested list, is sorted it needs to trigger an update event.

**Comment by lukasoppermann** [comment]
So I think this is currently not possible. What is missing is a way to specify which items are accepted. 

If you are interested I would love to accept a PR for an "acceptItem" option, which lets the user specify a function, only if the function returns true, it would allow the item to be nested.

Otherwise I would not know how this is possible with the current setup. I am sorry I can not be of more help. Let me know if there is any other thing to this, otherwise I will close this.

If you want to look into creating an "acceptItem" option, please open a new issue for this so we can discuss the details. Thank you.
