### ISSUE TITLE
Interface for working with jquery.

### ISSUE THREAD

**Issue by alexsilva** [lukasoppermann/html5sortable#535]
### supporting information:
- I use sortable version: 0.9.17
- I tested in the following browser (incl. versions): Chrome
- Windows, OS X/macOS, or Linux?: Windows

### How can the issue be reproduce the problem?
Please add a complete description of how to reproduce the problem.

In a project that uses exclusively jquery. It was strange for me to work with a function without the jquery apis.

### Thank you for contributing!
- Please make sure your contribution is in line with the contribution guidelines: 
  https://github.com/lukasoppermann/html5sortable/blob/master/CONTRIBUTING.md

- Participation in this open source project is subject to the Code of Conduct:
  https://github.com/lukasoppermann/html5sortable/blob/master/CODE_OF_CONDUCT.md

Before creating a feature requests, please review the existing feature requests and make sure there isn't one that already describes the feature you are missing:
https://github.com/lukasoppermann/html5sortable/issues?q=is%3Aopen+is%3Aissue+label%3Afeature

#### What's the feature?
Interface for working with jquery

```
/* simple jquery plugin */
jQuery.fn.sortable = function (options) {
    return $(sortable(this, options));
};

$(".column").sortable({
      acceptFrom: ".column",
      handle: '.card-header',
      hoverClass: "cursor-move",
      items: ":not(.unsort)",
      forcePlaceholderSize: true,
}).each(function () {
      this.addEventListener('sortupdate',function( e ) {
})
```

**Comment by lukasoppermann** [comment]
Hey, if you want to you could create an adaptor, similar to the one for Polymer: https://github.com/rodrigosancho/polymer-html5sortable

This would just be a simple wrapper that uses jquery and allows to work with the plugin the way you want. If you can afterwards add the link to your adapter to this Issue I am happy to add it to the docs.
