### ISSUE TITLE
Is it possible to run other than using classes?

### ISSUE THREAD

**Issue by piercemcgeough** [lukasoppermann/html5sortable#536]
Is it possible to do a loop over selectors to instantiate the sorter?

Instead of doing this
```
sortable('.sortable');
sortable('.sortable')[0].addEventListener('sortupdate', function(e) {});
```

I would like to this.... or similar
```
const sortableAreas = document.querySelectorAll('[data-dropzone]');
[].forEach.call(sortableAreas, function(sortableArea) {
    sortableArea.sortable()   // or  sortable(sortableArea)
    sortableArea.addEventListener('sortupdate', updateOrder);
});
```

**Comment by lukasoppermann** [comment]
That should be possible.
I think you can actually also provide a nodeList (https://github.com/lukasoppermann/html5sortable/blob/master/src/html5sortable.ts#L221)

So I would do it like this (not tested, let me know if you have further issues):

```
// this should create sortables for all elements with a data-dropzone attribute
const sortableAreas = sortable('[data-dropzone]');
sortableAreas.forEach(sortable, function(sortableArea) {
    // use sortable[0] to get the actual NodeElement and not the sortable wrapper
    sortable[0].addEventListener('sortupdate', updateOrder);
});
```

**Comment by piercemcgeough** [comment]
Thanks, it works great, just a slight change
```
sortableAreas.forEach(function(sortableArea) {
     sortableArea.addEventListener('sortupdate', updateOrder);
});
``` 

I do have an issue with upload data. Im using dropzone, so its a drag and drop.
But I get an error on the html5sortable "Cannot read property 'parentElement' of null".
 I thought it may have been related to this issue https://github.com/lukasoppermann/html5sortable/issues/328 however I don't think they are related

The issue continues even if I disable the dropzone.

I appear to be using version 0.9.8

HTML
```
<div class="card-body"
    data-dropzone
    data-dropzone-url="/store"
    data-dropzone-files-accepted="image/*"
>
    <ul class="gallery"
        data-sortable
        data-update-url="/updateOrder"
    >
        <li class="parent image-area" data-image-id="42">
            <img src="/preview/001.jpg" alt="" />
        </li>
        
        <li class="parent image-area" data-image-id="43">
            <img src="/preview/002.jpg" alt="" />
        </li>
    </ul>
</div> <!-- END .card-body -->
```

JS
```
var sortables = sortable('.affinity-sortable');

[].forEach.call(sortables, function(sortable) {
    sortable.addEventListener('sortupdate', updateOrder);
});

function updateOrder(e) {
    let imageIdsOrder = [];

    e.detail.destination.items.forEach(function(image) {
        imageIdsOrder.push(image.dataset.imageId);
    });

    $.ajax({
        url: this.dataset.updateUrl,
        data: {
            order: imageIdsOrder
        },
        type: "post",
    });
}
```

**Comment by lukasoppermann** [comment]
When does this arrow occur exactly? What do you do to produce it? Can you upload something to codepen so I can test it out?

**Comment by piercemcgeough** [comment]
It appears to be on the drop, so i am dragging a file from my desktop to the app into the dropzone, but the sort is just inside it too which is trying to pick up a drop i think.

Here is a pen. I can't see the error here but it may be pen issue not working as i expect with file uploads.

https://codepen.io/piercemcgeough/pen/RwWrWwX

**Comment by lukasoppermann** [comment]
When you drop a file? This would make sense, as this will trigger a drop event without the element having a parent. You can probably fix this by canceling the event and preventing it from bubbling up in the dropzone somehow.

**Comment by piercemcgeough** [comment]
Would the cancel need to be on the dropzone or the sortable? I've tried both but no joy.
Im not sure on how to fix that but i'll play about thanks.

**Comment by lukasoppermann** [comment]
Hey @piercemcgeough you would have to cancel it within the dropzone. What you are trying is to avoid the event bubbling up to the sortable which is "above" the dropzone in the event chain.

**Comment by lukasoppermann** [comment]
Closing this, please comment if you are still on it.
