### ISSUE TITLE
acceptFrom only same class

### ISSUE THREAD

**Issue by paolodeferre** [lukasoppermann/html5sortable#537]
I'm using the release v0.9.16 of the plugin, combined with Jquery 3.4. It works perfect on my list but I need another feature and I don't know if it is possible or if there is a possible workaround to solve my issue.

```
<ul>
	<li class="type_one">My element of type 1</li>
	<li class="type_one">My element of type 1</li>
	<li class="type_two">My element of type 2</li>
	<li class="type_two">My element of type 2</li>
	<li class="type_two">My element of type 2</li>
	<li class="type_two">My element of type 2</li>
	<li class="type_three">My element of type 3</li>
	<li class="type_three">My element of type 3</li>
	<li class="type_three">My element of type 3</li>
</ul>
```

What I need is to allow user to sort **ONLY** items with the same class between them (eg. `type_one`). The option `acceptFrom` is not relative to each iteam individually then I can not use any setup like `acceptFrom: $(this).attr('class')`...

Thanks.

**Comment by lukasoppermann** [comment]
I am not sure I understand you correctly.

You want the user to only move e.g. type_one items between position 1 and 2 in your example?

Can't you just use 3 sortables in this case?

**Comment by paolodeferre** [comment]
Hello,

Thank you for the answer. I need to allow sorting only type_one items between themselves, type_two items between themselve and type_three items between themselves. Those items are included in the same UL list.

In my code sample I could indeed do 3 sortable, but in reality it's a huge list (~1000 items) and I don't control the number of different classes.

**Comment by lukasoppermann** [comment]
Ahh, okay. Sorry to say this, but that is not a case that is currently supported. `acceptFrom` is supposed to be used when sorting between different sortables.

Sorry I can not help you more. 😞
