### ISSUE TITLE
When forcePlaceholderSize: true, there is additional padding added making the item bigger than the original

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#547]
**Describe the bug**
When the sortable items `li` have padding, this padding is added on top of the width for the placeholder, if `forcePlaceholderSize` is set to `true`.

**To Reproduce**
1. Go to https://codepen.io/lukasoppermann/pen/WNrMvMb
2. Drag and drop item

**Expected behavior**
The width is the exact width of the original item

**Test Case**
https://codepen.io/lukasoppermann/pen/WNrMvMb

**System (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 83

**Comment by kaffarell** [comment]
This is fixed with the most recent version ( [codepen](https://codepen.io/kaffarell/pen/MWKzqLK) )
(Ubuntu, Chrome 83)
