### ISSUE TITLE
Comparison with RubaXa/Sortable

### ISSUE THREAD

**Issue by dandv** [lukasoppermann/html5sortable#57]
Salut Alexandru,

How does this library compare with @rubaxa's [Sortable](https://github.com/rubaxa/sortable) ?

**Comment by voidberg** [comment]
Salut Dan,

I did not know about this library but from a quick glance it looks more advanced than this one (touch support, jQuery free, Meteor support). They don't say anything about browser versions though.

We're planning on adding some of those features ourselves, like touch support, more events and removing the need for jQuery but I don't have an ETA right now.

**Comment by dandv** [comment]
Plus touch, minus jQuery... sounds like Sortable. How about joining efforts?

**Comment by haus23** [comment]
+1 for more Events
+1 for $-free

But
-1 for joining. Please keep this project that simple!
