### ISSUE TITLE
VanillaJs

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#60]
Hey @voidberg,

what do you think about ditching frameworks and just make it work with vanillajs?

Maybe in a way that people who want jQuery for backwards compatibility could plug it in?

**Comment by dandv** [comment]
He [plans to do that](https://github.com/voidberg/html5sortable/issues/57#issuecomment-64565869). In the meantime you can use @rubaxa's [Sortable](https://github.com/RubaXa/Sortable), which supports touch devices too.

**Comment by lukasoppermann** [comment]
Hey @voidberg, 

I build a sortable as well https://github.com/lukasoppermann/engine-sortable without jquery. So basically I had to write my own "jquery" for a lot of repeating tasks.

I see only 2 sensible ways here:
- just keep jquery
- (better but more work) write wrappers for everything that is a jquery.fn and let users just write their own implementation inside so you use _select.byClass('xzy') and the user can just overwrite the methods of select. (Or something similar)

What do you think about this? I would like to merge my project with this one here (as in contribute the parts I feel are missing) and it would be handy to know the direction of this project to do so.

Thanks.

**Comment by nazar-pc** [comment]
VanillaJS edition is waiting for review: #204
