### ISSUE TITLE
Cloning a sortable element and appending the cloned element into the list results in an unsortable item

### ISSUE THREAD

**Issue by brookswift** [lukasoppermann/html5sortable#61]
http://jsfiddle.net/w1qgL6uw/

Using 0.1.6, I apply sortable to a ul. Then I clone a li and append it to the ul. The new li element is not sortable.

**Comment by SpikedKira** [comment]
http://api.jquery.com/clone/
you need to pass 'true' to your clone method call to copy the events
you can also call a destroy on the sortable and re-instantiate or call .sortable("reload")

**Comment by brookswift** [comment]
Thanks, I was using destroy and re-instantiation, but reload is easier.
However, clone(true) and clone(true, true) for deep cloning both don't
work. Is there a registry of draggable elements somewhere that could have
new elements added instead of unloading and reloading sortable?

I'm switching to using .sortable("reload") for now.

**Comment by SpikedKira** [comment]
$(caller).data('opts').items is the collection of sortable items.

I would not recommend changing that directly, but you could.  The reload method is quite light-weight.

Sorry, I forgot that it does maintain that list of items for some purposes.
