### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by jacobsvante** [lukasoppermann/html5sortable#63]
Would be nice to have when using `browserify`.

**Comment by lukasoppermann** [comment]
https://www.npmjs.com/package/html5sortable

**Comment by jacobsvante** [comment]
That's not a node package though. Basically the current release on NPM requires just the same effort as when using `bower`.

What's nice with a proper node release would be the possibility to just do the following within the browserify-run code:

``` js
require('htm5sortable')
```

Now instead I have to use `browserify-shim` configuration like this in my `package.json` before being able to require it:

``` json
  "browser": {
    "html5sortable": "./node_modules/html5sortable/src/html.sortable.js"
  },
  "browserify-shim": {
    "html5sortable": {
      "exports": "$.fn.sortable"
    }
  }
```

**Comment by lukasoppermann** [comment]
Well, could you send a PR to fix this?

**Comment by jacobsvante** [comment]
There ya go :-)

**Comment by jacobsvante** [comment]
Don't forget to [update the version](https://docs.npmjs.com/getting-started/publishing-npm-packages) on NPM also! It's still on `0.2.0`.

**Comment by lukasoppermann** [comment]
Thanks, I forgot that npm is not like bower and does not auto-fetch the newly tagged versions. Will be adding a publish task later so this does not happen again. :)

**Comment by jacobsvante** [comment]
:+1:
