### ISSUE TITLE
Don't create extra item in connected list

### ISSUE THREAD

**Issue by jacobsvante** [lukasoppermann/html5sortable#65]
When I move one item from a connected list to the other it will create a placeholder, thus creating one extra item in that list. Would it be possible to keep the placeholder in there but move the first item to a connected list before or after the one the placeholder was put into? Here's a more visual example of what I mean:

![screen shot 2014-12-19 at 12 14 44](https://cloud.githubusercontent.com/assets/190835/5503593/1d0f801c-8779-11e4-8bef-12ae5bbf1a71.png)
I moved `light blue Item 3` over to the yellow list, thus moving `yellow Item 1` to the blue list.

It feels like both ways have their purpose so I think this should be configurable if implemented.

**Comment by lukasoppermann** [comment]
Huiii, this seems complicated, what happens if you have more than 2 connected lists? It seems an interesting idea, would you like to send a PR for this?
