### ISSUE TITLE
There is a serialize but no deserialize 

### ISSUE THREAD

**Issue by arczas89** [lukasoppermann/html5sortable#697]
Hi,

How to deseriaze serialzed object ? How to recover serialize object to working sortable list?

**Comment by lukasoppermann** [comment]
Hey @arczas89,

not sure I get you.

So to serialize the list you use: https://github.com/lukasoppermann/html5sortable#serialize

If you want to build a list, you need to build it via js and initialize a html5Sortable on top of the list.

There is currently not method that builds a sortable from an array or object.
