### ISSUE TITLE
Strange behavior of 'maxItems' property

### ISSUE THREAD

**Issue by r34117y** [lukasoppermann/html5sortable#713]
When I initialize my sortable with `maxItems : 1` the container doesn't allow to drop any items. 

With `maxItems : 2` it allows to drop one item. The container is empty (no hidden elements, nothing).

I think that placeholder element is counted, but that would be very counter-intuitive.

Anouther possible cause is that I initialize many containers at once (each table cell is a drop container).

Code:
```
sortable('td.label', {
            acceptFrom : '.unused, .label',
            maxItems : 2, // allows one item to be dropped
            placeholderClass: 'list-group-item',
            dropTargetContainerClass: 'bg-destroy'
        })
```

**Comment by lukasoppermann** [comment]
Hey @r34117y that is definitely not expected.

Would you be able to investigate the issue and maybe send a PR to fix it?
 
The issue could possibly be here: https://github.com/lukasoppermann/html5sortable/blob/master/src/html5sortable.ts#L632
If the idea you suggested is true we would need to replace `sortableElement.children` with a function may `getSortableChildren(sortableElement)`. This would probably need to be used everywhere, where `sortableElement.children` is used now. 

But to beging with you could add the function and replace this one instance to fix this specific bug.

**Comment by lukasoppermann** [comment]
Hey @r34117y this should be fixed now. Let me know if it works.
