### ISSUE TITLE
Use on delegated binding.

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/html5sortable#73]
We should swap out the 

``` javascript
$(xyz).on(...
```

for something like

``` javascript
$('body').on('...', '.sortable-item',...
```

because this would remove the need for reload when adding items to a list. We should probably also bind the sortable list this way, I would certainly need this and I guess some of people building sortable columns would appreciate this as well, so a new column which contains sortables can be added later on.

This would also solve #56.

The only part which needs a tiny bit more thought to it, is the binding on `dragover` because it binds to the list and the items. I would appreciate a pull for #72 and working more on this so the code gets easier, afterwards it will be much easier to du this.

``` javascript
.add([this, placeholder]).on('dragover.h5s dragenter.h5s drop.h5s', function(e) {
```

**Comment by pavlm** [comment]
Its a very desired change for dynamic lists.

**Comment by lukasoppermann** [comment]
I will be working on this soon, I believe it might bring some problems with it though, but I will make it work somehow. I need to refactor a little bit first though.

**Comment by lukasoppermann** [comment]
Not using jQuery anymore. `reload`ing a sortable brings the same result.
