### ISSUE TITLE
When drop is finished all items below placeholder flicker.

### ISSUE THREAD

**Issue by k2tomasz** [lukasoppermann/html5sortable#771]
Flickering happens because for a split second items move up when placeholder is removed and then move down when dropped item is added.

You can see this i this short demo I made:

https://www.loom.com/share/7fbde267cfd2444e86c157e35a0971df

sortable(cardListSelector, {
            acceptFrom: '.cards-wrap',
            forcePlaceholderSize: true,
            placeholder: '<div class="card-dropzone"></div>'
});

Any ideas how to fix it?

**Comment by lukasoppermann** [comment]
Maybe by using replaceChild instead? Didn't try it, but if you could give it a try and send a PR that would be neat.

https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild

I am thinking just replacing the placeholder node.

**Comment by k2tomasz** [comment]
@lukasoppermann changing insert to is not enough. Additionally dragging.style.display needs to be restored before or immediately after replaceWith. I will push a PR shortly.
