### ISSUE TITLE
React usage

### ISSUE THREAD

**Issue by cuongcua90** [lukasoppermann/html5sortable#80]
How can I use this library on React?

**Comment by lukasoppermann** [comment]
I never used react, did you find out how to use it? If so, I would appreciate if you could add a short explanation so I can add it to the docs.

**Comment by CWSites** [comment]
I use this with React, there isn't anything special needed as far as I know. I import the library at the top of my file per the docs.

I initialize once the component mounts
```
componentDidMount() {
    sortable('.sortable', {
        forcePlaceholderSize: true,
        placeholderClass: 'sortable-placeholder',
        hoverClass: 'is-hovered'
    });
}
```

Then I add the necessary classes to the sortable container and sortable elements.
