### ISSUE TITLE
Angular directive does not work when $compileProvider.debugInfoEnabled(false);

### ISSUE THREAD

**Issue by godza** [lukasoppermann/html5sortable#84]
Angular developers recommend turning off debug info to speed up angular apps in production environments. Consequence of this action is that scope() functions stops working, because scope() functions are intended to be used only for development (and batarang extension). However, html5sortable directive heavily depend on scope() functions, so in production environments angular directive does not work.

Here is the official document stating these facts https://docs.angularjs.org/guide/production 

Regards

**Comment by lukasoppermann** [comment]
This seems to be related to https://github.com/voidberg/html5sortable/issues/86.
If you want to send a PR fixing this, I am happy to merge it.
