### ISSUE TITLE
this sortable deactive click action

### ISSUE THREAD

**Issue by 9px** [lukasoppermann/html5sortable#85]
when i insert an input in the sortable items, the click on the text input doesn't work!
for example if the input (in the ul.sortable > li) have some text, when i click on the center of text, the cursor must go to the point, but the cursor appear in the start of text!
(i use handle but the problem remain unsolved)

**Comment by lukasoppermann** [comment]
It does work for me, do you also have the issue here: https://jsfiddle.net/zbLb80mn/5/ ?

**Comment by 9px** [comment]
@lukasoppermann thanks. no i havn't problem with your Jsfiddle sample. i must see my code for the problem.

**Comment by lukasoppermann** [comment]
Okay, please let me know if you find a solution so I can close this.
