### ISSUE TITLE
Brave browser not supported in 0.13.3 version

### ISSUE THREAD

**Issue by martinbarilik** [lukasoppermann/html5sortable#859]
Hi, pretty straight forward. The library is not working on latest brave browser version 1.34.80, not sure if it worked before.

**Comment by lukasoppermann** [comment]
I am not sure either. Do you have a fix for this available? If so could you send a PR?

**Comment by martinbarilik** [comment]
Time has passed, i do not remember the exact conditions, but it's working for me now. Maybe some brave update has fixed it. 

Consider it not relevant for the time being, if anything will come up, i'll reopen.
