### ISSUE TITLE
Angular directive doesn't support "controller as" syntax

### ISSUE THREAD

**Issue by ronnieoverby** [lukasoppermann/html5sortable#86]
Working with traditional use with $scope:
http://codepen.io/ronnieoverby/pen/vEjroy

Not working with controller as syntax:
http://codepen.io/ronnieoverby/pen/RNyBNp

This is unfortunate for me because the way your executing the callback is forcing me to deviate from the normal architecture of my app and use $scope.

[An approach that would probably solve the issue](http://stackoverflow.com/a/19960066/64334) (but not be backward compatible) is to parse the callback expression and force the developer to be explicit about arguments.

**Comment by lukasoppermann** [comment]
Hey @ronnieoverby I never really used angular, could you maybe explain in short what the disadvantage of the controller syntax is? And if it is not too bad, send a PR? Would that be something that everybody can use?

**Comment by ronnieoverby** [comment]
http://stackoverflow.com/questions/16619740/angular-should-i-use-this-or-scope

I don't have time to implement the fix to this issue. Yes I think everyone could use the fix, especially me.
