### ISSUE TITLE
Issue with nesting and sortable

### ISSUE THREAD

**Issue by kipwilliams** [lukasoppermann/html5sortable#89]
You cannot have nested lists of sortables.  To fix this add a stop progagation to 

 items.on('dragstart.h5s', function (e) {
        e.stopPropagation(); <<---- add this line

var dt = e.originalEvent.dataTransfer;
        dt.effectAllowed = 'move';
        dt.setData('text', '');

**Comment by Bombshock** [comment]
+1

**Comment by lukasoppermann** [comment]
fixing nested list bug #68
