### ISSUE TITLE
Understanding Ghost / Preview Styling options

### ISSUE THREAD

**Issue by gregpettit** [lukasoppermann/html5sortable#94]
If I load up the plain (non-Angular) HTML sample page, I see two different behaviours for "ghosts" that are attached to the cursor during drag operations:
1. In the very first list, when you drag an item in Chrome, the ghost fades to nothing (gradient from original to transparency) around the edges.
2. In the grid list, which is initialized with the same options, the ghost is just a slightly transparent clone of the original. In other words it doesn't fade as a "gradient", the whole element is just faded out a bit.

I can't figure out how to intentionally get this second behaviour. In my application, I keep getting the first.

I couldn't discern from the code how to just append a ghost to the DOM. Is it being created at the browser API level? (vs. jQuery UI where it is literally a new element appended to the document). I did discover a class for general styling purposes; however, even when this style does not include a "fade to transparent edges" effect, there is one in place.

Normally I'd be happy just writing it off to the HTML5 implementation just "doing it" for me but I can see examples in the same browser on the same page with the same JS initialization (another example is the connected list) in which that fade doesn't happen. I must be missing something glaringly obvious!

**Comment by lukasoppermann** [comment]
Sorry, I could not recreate any of the issues. For me it just fades everywhere. Can you maybe attach screenshots, ora video?

You are using the provided example, correct? Or are you rolling your own?

**Comment by gregpettit** [comment]
More or less the provided example. The only change I made was loading jQuery 1.11 from the CDN.

Here's the screen shot:

![sortable](https://cloud.githubusercontent.com/assets/439648/7277105/048e1b1a-e8dc-11e4-8d6b-c8f42609769c.png)

One thing I just noticed is that the "shape" of the gradient fade depends on where I click with the mouse. It seems to "radiate" out from the point of clicking. So for example if I click lower-left, it is almost opaque in the lower left and then fades out before it hits the edge of the "ghost" element. If I click close to the middle, you see what is in the attached screenshot.

I believe that the simple reduction in opacity is from the browser-level HTML5 API. The gradient seems to be provided by JS or CSS.

---

So, the follow-up question would be: is there a known JavaScript API or CSS properties for styling that "ghost"?

**Comment by lukasoppermann** [comment]
I am working on a way to style it, there is a complicated solution. You can not just style it (sadly). Basically the browser takes a screenshot of your element at the time when the drag event hits. 

Your image looks pretty weird, is this version online?

**Comment by gregpettit** [comment]
I don't mind the default "screen shot" version. It's the gradient version that I do not want. It seems to be the "override" but I don't know where it's coming from. The sample is not online right now, but I could put it online. Let's see here....

**Comment by gregpettit** [comment]
http://sandbox.gregpettit.ca/sortable.html

**Comment by lukasoppermann** [comment]
Hey, so if I view it, it works like a charm. I am running Chrome 42 (Mac) and I tried it in FF 37 as well.

Could it be something with your monitor? Were you able to replicate the issue on a different system?

**Comment by gregpettit** [comment]
Can't be the monitor. On the SAME page, there is different behaviour.

Faded at edges like gradient: Sortable List, Exclude Items, Sortable List with sublist, Add item to sortable

Uniform reduction of opacity: Sortable Grid, Connected Sortable Lists

---

Same behaviour in Firefox 37.0.1 and Chrome 41.0.2272.118 m

**Comment by gregpettit** [comment]
It's so weird. Although I should have done it in the first place, I finally gave it a go on IE (same machine) and it has the consistently "uniform reduction of opacity" behaviour.

Ultimately, seems like a browser quirk/bug and probably not anything I can control. But I'm curious as heck about why on the same page for Fx and Chrome there is different behaviour. If I could identify the common factor, I might be able to hack in a bandaid solution.

**Comment by lukasoppermann** [comment]
Okay, so I will close it for now, if you have more information or a solution, please let me know! Thanks.
