### ISSUE TITLE
Remove the hidden after drop

### ISSUE THREAD

**Issue by NodexTech** [lukasoppermann/html5sortable#98]
Your plugin doesn't remove the dragging LI that it creates which leads to unexpected behaviour in forms - namely that it leaves the order (hidden) the same as when it started.

Is this by design or a bug?

**Comment by topguns** [comment]
No getting anything infor

**Comment by NodexTech** [comment]
Is that even a real sentence?

**Comment by lukasoppermann** [comment]
Sorry, I don't really get it. Are you saying, that the class `sortable-dragging` is not removed on release if the dragged item? 

I could not reproduce the issue, so please upload a test case and tell me your environment and setup.

**Comment by NodexTech** [comment]
When dragging and sorting the element that's dragging is NOT removed on drop. The code that your repository is based on works fine so there must be something that got lost when it was cloned.
 Unfortunately I've removed the repo from my app now and replaced it with something that's working and don't have time to put it back sorry.

**Comment by lukasoppermann** [comment]
Hmm, well, you have to at least tell me the entire setup. I do not see any issue at the moment, and if I don't know how you encountered it I can not try to fix it.

Can you tell me:
- Browser & version
- Win/Mac/Linux?
- Version of this plugin you used?
- Other plugins you use?

Just to make sure, when you reorder the items, they are duplicated, correct? E.g. you move Item 1 at Pos 3, now you have Item 1 twice?

**Comment by NodexTech** [comment]
Chrome and Firefox (latest for both)
Windows, Mac and Linux and Phone (android 5.0 w/ chrome)
Latest plugin version.
No other plugins, only jquery as a llibrary.

**Comment by lukasoppermann** [comment]
Okay, and the behaviour I described was what you are referring to? 

> Just to make sure, when you reorder the items, they are duplicated, correct? E.g. you move Item 1 at Pos 3, now you have Item 1 twice?

Did you install the code from bower?

**Comment by NodexTech** [comment]
Yes that's correct. Every moved item ends up with a hidden clone of itself.

No I did not install from bower.

**Comment by lukasoppermann** [comment]
Okay, can you please update to the latest version (from today) and check if it copies, or provide a demo of the code where it was not functioning? If its a git repo, I guess you would have an old commit with it included? Thanks.

**Comment by NodexTech** [comment]
Hi.

Yes it's still doing it. 

Please see attached image 
![role](https://cloud.githubusercontent.com/assets/6095811/7371468/1705efd4-edb9-11e4-98b1-e45335067f80.png)

As you can clearly see, there are three LI elements but only two LI's in the UI, the third is "display:none" but it should not even be there

Hope this helps

**Comment by lukasoppermann** [comment]
Wow, well, actually, is there a way to get to the live code?

**Comment by NodexTech** [comment]
Unfortunately it's behind a secure client site, I can't recreate the environment it without exposing a development address.

I'll see if I can clone just that part of it somehow for you.

A quick comparison of code suggests the problem may lay in that the dragging element is called "dragging" and also "dragging" is assigned if something is being dragged - this is just a quick glance and comparison of working code from which yours (seems to be) based (https://github.com/farhadi/html5sortable)

**Comment by lukasoppermann** [comment]
A clone would be awesome. I will also investigate your idea on the problem, although it is hard to test without an error case. :) 

If you can recreate the problem in the examples.html file this would also help me. Whichever is easier for you. Thanks.

**Comment by lukasoppermann** [comment]
@NodexTech Any news on the clone?

**Comment by NodexTech** [comment]
Sorry, I've been mega busy with work and it slipped my mind, I'll try and get it sorted this week

**Comment by kaffarell** [comment]
This Issue has been closed due to inactivity
